/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * Extended bot information.
 */
@JsonPropertyOrder({
  BotInfo.JSON_PROPERTY_CATEGORY,
  BotInfo.JSON_PROPERTY_PROVIDER,
  BotInfo.JSON_PROPERTY_PROVIDER_URL,
  BotInfo.JSON_PROPERTY_NAME,
  BotInfo.JSON_PROPERTY_IDENTITY,
  BotInfo.JSON_PROPERTY_CONFIDENCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class BotInfo {
  public static final String JSON_PROPERTY_CATEGORY = "category";
  @jakarta.annotation.Nonnull
  private String category;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nonnull
  private String provider;

  public static final String JSON_PROPERTY_PROVIDER_URL = "provider_url";
  @jakarta.annotation.Nullable
  private String providerUrl;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  /**
   * The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider’s customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity. 
   */
  public enum IdentityEnum {
    VERIFIED(String.valueOf("verified")),
    
    SIGNED(String.valueOf("signed")),
    
    SPOOFED(String.valueOf("spoofed")),
    
    UNKNOWN(String.valueOf("unknown"));

    private String value;

    IdentityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IdentityEnum fromValue(String value) {
      for (IdentityEnum b : IdentityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_IDENTITY = "identity";
  @jakarta.annotation.Nonnull
  private IdentityEnum identity;

  /**
   * Confidence level of the bot identification.
   */
  public enum ConfidenceEnum {
    LOW(String.valueOf("low")),
    
    MEDIUM(String.valueOf("medium")),
    
    HIGH(String.valueOf("high"));

    private String value;

    ConfidenceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ConfidenceEnum fromValue(String value) {
      for (ConfidenceEnum b : ConfidenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @jakarta.annotation.Nonnull
  private ConfidenceEnum confidence;

  public BotInfo() { 
  }

  public BotInfo category(@jakarta.annotation.Nonnull String category) {
    this.category = category;
    return this;
  }

  /**
   * The type and purpose of the bot.
   * @return category
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCategory(@jakarta.annotation.Nonnull String category) {
    this.category = category;
  }


  public BotInfo provider(@jakarta.annotation.Nonnull String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * The organization or company operating the bot.
   * @return provider
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@jakarta.annotation.Nonnull String provider) {
    this.provider = provider;
  }


  public BotInfo providerUrl(@jakarta.annotation.Nullable String providerUrl) {
    this.providerUrl = providerUrl;
    return this;
  }

  /**
   * The URL of the bot provider's website.
   * @return providerUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProviderUrl() {
    return providerUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderUrl(@jakarta.annotation.Nullable String providerUrl) {
    this.providerUrl = providerUrl;
  }


  public BotInfo name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The specific name or identifier of the bot.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public BotInfo identity(@jakarta.annotation.Nonnull IdentityEnum identity) {
    this.identity = identity;
    return this;
  }

  /**
   * The verification status of the bot's identity:  * `verified` - well-known bot with publicly verifiable identity, directed by the bot provider.  * `signed` - bot that signs its platform via Web Bot Auth, directed by the bot provider’s customers.  * `spoofed` - bot that claims a public identity but fails verification.  * `unknown` - bot that does not publish a verifiable identity. 
   * @return identity
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IDENTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public IdentityEnum getIdentity() {
    return identity;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentity(@jakarta.annotation.Nonnull IdentityEnum identity) {
    this.identity = identity;
  }


  public BotInfo confidence(@jakarta.annotation.Nonnull ConfidenceEnum confidence) {
    this.confidence = confidence;
    return this;
  }

  /**
   * Confidence level of the bot identification.
   * @return confidence
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ConfidenceEnum getConfidence() {
    return confidence;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfidence(@jakarta.annotation.Nonnull ConfidenceEnum confidence) {
    this.confidence = confidence;
  }


  /**
   * Return true if this BotInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BotInfo botInfo = (BotInfo) o;
    return Objects.equals(this.category, botInfo.category) &&
        Objects.equals(this.provider, botInfo.provider) &&
        Objects.equals(this.providerUrl, botInfo.providerUrl) &&
        Objects.equals(this.name, botInfo.name) &&
        Objects.equals(this.identity, botInfo.identity) &&
        Objects.equals(this.confidence, botInfo.confidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, provider, providerUrl, name, identity, confidence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BotInfo {\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    providerUrl: ").append(toIndentedString(providerUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

