/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fingerprint.model.RuleActionHeaderField;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * The set of header modifications to apply, in the following order: remove, set, append.
 */
@JsonPropertyOrder({
  RequestHeaderModifications.JSON_PROPERTY_REMOVE,
  RequestHeaderModifications.JSON_PROPERTY_SET,
  RequestHeaderModifications.JSON_PROPERTY_APPEND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class RequestHeaderModifications {
  public static final String JSON_PROPERTY_REMOVE = "remove";
  @jakarta.annotation.Nullable
  private List<String> remove = new ArrayList<>();

  public static final String JSON_PROPERTY_SET = "set";
  @jakarta.annotation.Nullable
  private List<RuleActionHeaderField> set = new ArrayList<>();

  public static final String JSON_PROPERTY_APPEND = "append";
  @jakarta.annotation.Nullable
  private List<RuleActionHeaderField> append = new ArrayList<>();

  public RequestHeaderModifications() { 
  }

  public RequestHeaderModifications remove(@jakarta.annotation.Nullable List<String> remove) {
    this.remove = remove;
    return this;
  }

  public RequestHeaderModifications addRemoveItem(String removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

  /**
   * The list of headers to remove.
   * @return remove
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REMOVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRemove() {
    return remove;
  }


  @JsonProperty(value = JSON_PROPERTY_REMOVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemove(@jakarta.annotation.Nullable List<String> remove) {
    this.remove = remove;
  }


  public RequestHeaderModifications set(@jakarta.annotation.Nullable List<RuleActionHeaderField> set) {
    this.set = set;
    return this;
  }

  public RequestHeaderModifications addSetItem(RuleActionHeaderField setItem) {
    if (this.set == null) {
      this.set = new ArrayList<>();
    }
    this.set.add(setItem);
    return this;
  }

  /**
   * The list of headers to set, overwriting any existing headers with the same name.
   * @return set
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RuleActionHeaderField> getSet() {
    return set;
  }


  @JsonProperty(value = JSON_PROPERTY_SET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSet(@jakarta.annotation.Nullable List<RuleActionHeaderField> set) {
    this.set = set;
  }


  public RequestHeaderModifications append(@jakarta.annotation.Nullable List<RuleActionHeaderField> append) {
    this.append = append;
    return this;
  }

  public RequestHeaderModifications addAppendItem(RuleActionHeaderField appendItem) {
    if (this.append == null) {
      this.append = new ArrayList<>();
    }
    this.append.add(appendItem);
    return this;
  }

  /**
   * The list of headers to append.
   * @return append
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APPEND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RuleActionHeaderField> getAppend() {
    return append;
  }


  @JsonProperty(value = JSON_PROPERTY_APPEND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppend(@jakarta.annotation.Nullable List<RuleActionHeaderField> append) {
    this.append = append;
  }


  /**
   * Return true if this RequestHeaderModifications object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestHeaderModifications requestHeaderModifications = (RequestHeaderModifications) o;
    return Objects.equals(this.remove, requestHeaderModifications.remove) &&
        Objects.equals(this.set, requestHeaderModifications.set) &&
        Objects.equals(this.append, requestHeaderModifications.append);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remove, set, append);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestHeaderModifications {\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("    append: ").append(toIndentedString(append)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

