/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.sdk.JSON;


/**
 * Browser-reported touch capabilities.
 */
@JsonPropertyOrder({
  TouchSupport.JSON_PROPERTY_TOUCH_EVENT,
  TouchSupport.JSON_PROPERTY_TOUCH_START,
  TouchSupport.JSON_PROPERTY_MAX_TOUCH_POINTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class TouchSupport {
  public static final String JSON_PROPERTY_TOUCH_EVENT = "touch_event";
  @jakarta.annotation.Nullable
  private Boolean touchEvent;

  public static final String JSON_PROPERTY_TOUCH_START = "touch_start";
  @jakarta.annotation.Nullable
  private Boolean touchStart;

  public static final String JSON_PROPERTY_MAX_TOUCH_POINTS = "max_touch_points";
  @jakarta.annotation.Nullable
  private Long maxTouchPoints;

  public TouchSupport() { 
  }

  public TouchSupport touchEvent(@jakarta.annotation.Nullable Boolean touchEvent) {
    this.touchEvent = touchEvent;
    return this;
  }

  /**
   * Get touchEvent
   * @return touchEvent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOUCH_EVENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTouchEvent() {
    return touchEvent;
  }


  @JsonProperty(value = JSON_PROPERTY_TOUCH_EVENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTouchEvent(@jakarta.annotation.Nullable Boolean touchEvent) {
    this.touchEvent = touchEvent;
  }


  public TouchSupport touchStart(@jakarta.annotation.Nullable Boolean touchStart) {
    this.touchStart = touchStart;
    return this;
  }

  /**
   * Get touchStart
   * @return touchStart
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOUCH_START, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTouchStart() {
    return touchStart;
  }


  @JsonProperty(value = JSON_PROPERTY_TOUCH_START, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTouchStart(@jakarta.annotation.Nullable Boolean touchStart) {
    this.touchStart = touchStart;
  }


  public TouchSupport maxTouchPoints(@jakarta.annotation.Nullable Long maxTouchPoints) {
    this.maxTouchPoints = maxTouchPoints;
    return this;
  }

  /**
   * Get maxTouchPoints
   * @return maxTouchPoints
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_TOUCH_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getMaxTouchPoints() {
    return maxTouchPoints;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_TOUCH_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxTouchPoints(@jakarta.annotation.Nullable Long maxTouchPoints) {
    this.maxTouchPoints = maxTouchPoints;
  }


  /**
   * Return true if this TouchSupport object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TouchSupport touchSupport = (TouchSupport) o;
    return Objects.equals(this.touchEvent, touchSupport.touchEvent) &&
        Objects.equals(this.touchStart, touchSupport.touchStart) &&
        Objects.equals(this.maxTouchPoints, touchSupport.maxTouchPoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(touchEvent, touchStart, maxTouchPoints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TouchSupport {\n");
    sb.append("    touchEvent: ").append(toIndentedString(touchEvent)).append("\n");
    sb.append("    touchStart: ").append(toIndentedString(touchStart)).append("\n");
    sb.append("    maxTouchPoints: ").append(toIndentedString(maxTouchPoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

