/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The type and purpose of the bot.
 */
public enum BotInfoCategory {
  ADVERTISING_AND_MARKETING("advertising_and_marketing"),

  AGGREGATOR("aggregator"),

  AI_AGENT("ai_agent"),

  AI_ASSISTANT("ai_assistant"),

  AI_BROWSER("ai_browser"),

  AI_CRAWLER("ai_crawler"),

  AI_SEARCH("ai_search"),

  BROWSER_AUTOMATION("browser_automation"),

  ECOMMERCE("ecommerce"),

  MONITORING_AND_ANALYTICS("monitoring_and_analytics"),

  OTHER("other"),

  SCRAPING("scraping"),

  SECURITY("security"),

  SEARCH_ENGINE_CRAWLER("search_engine_crawler"),

  SEARCH_ENGINE_OPTIMIZATION("search_engine_optimization"),

  UNKNOWN("unknown"),

  UNSUPPORTED_VALUE_SDK_UPGRADE_REQUIRED("unsupported_value_sdk_upgrade_required");

  private String value;

  BotInfoCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BotInfoCategory fromValue(String value) {
    for (BotInfoCategory b : BotInfoCategory.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNSUPPORTED_VALUE_SDK_UPGRADE_REQUIRED;
  }
}
