/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.v4.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.v4.sdk.JSON;


/**
 * Canvas fingerprint containing winding flag plus geometry/text hashes.
 */
@JsonPropertyOrder({
  Canvas.JSON_PROPERTY_WINDING,
  Canvas.JSON_PROPERTY_GEOMETRY,
  Canvas.JSON_PROPERTY_TEXT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Canvas {
  public static final String JSON_PROPERTY_WINDING = "winding";
  @jakarta.annotation.Nullable
  private Boolean winding;

  public static final String JSON_PROPERTY_GEOMETRY = "geometry";
  @jakarta.annotation.Nullable
  private String geometry;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nullable
  private String text;

  public Canvas() { 
  }

  public Canvas winding(@jakarta.annotation.Nullable Boolean winding) {
    this.winding = winding;
    return this;
  }

  /**
   * Get winding
   * @return winding
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WINDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWinding() {
    return winding;
  }


  @JsonProperty(value = JSON_PROPERTY_WINDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWinding(@jakarta.annotation.Nullable Boolean winding) {
    this.winding = winding;
  }


  public Canvas geometry(@jakarta.annotation.Nullable String geometry) {
    this.geometry = geometry;
    return this;
  }

  /**
   * Hash of geometry rendering output or `unsupported` markers.
   * @return geometry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GEOMETRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGeometry() {
    return geometry;
  }


  @JsonProperty(value = JSON_PROPERTY_GEOMETRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGeometry(@jakarta.annotation.Nullable String geometry) {
    this.geometry = geometry;
  }


  public Canvas text(@jakarta.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Hash of text rendering output or `unsupported` markers.
   * @return text
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = text;
  }


  /**
   * Return true if this Canvas object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Canvas canvas = (Canvas) o;
    return Objects.equals(this.winding, canvas.winding) &&
        Objects.equals(this.geometry, canvas.geometry) &&
        Objects.equals(this.text, canvas.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(winding, geometry, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Canvas {\n");
    sb.append("    winding: ").append(toIndentedString(winding)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

