/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * Native, SDK-collected mobile device identification signals (manufacturer, model, and OS version). Structurally separate from the top-level `device`, `os`, and `os_version` fields and from `browser_details`, all of which are derived from user-agent parsing rather than native SDK signals.
 */
@JsonPropertyOrder({
  DeviceDetails.JSON_PROPERTY_DEVICE_MANUFACTURER,
  DeviceDetails.JSON_PROPERTY_DEVICE_MODEL,
  DeviceDetails.JSON_PROPERTY_OS_VERSION
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.24.0")
public class DeviceDetails {
  public static final String JSON_PROPERTY_DEVICE_MANUFACTURER = "device_manufacturer";
  @jakarta.annotation.Nullable private String deviceManufacturer;

  public static final String JSON_PROPERTY_DEVICE_MODEL = "device_model";
  @jakarta.annotation.Nullable private String deviceModel;

  public static final String JSON_PROPERTY_OS_VERSION = "os_version";
  @jakarta.annotation.Nullable private String osVersion;

  public DeviceDetails() {}

  public DeviceDetails deviceManufacturer(@jakarta.annotation.Nullable String deviceManufacturer) {
    this.deviceManufacturer = deviceManufacturer;
    return this;
  }

  /**
   * Raw device manufacturer string as reported by the device OS. Not normalized: casing is vendor-defined (samsung, Xiaomi, OPPO, HUAWEI). Always `Apple` on iOS.
   * @return deviceManufacturer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_MANUFACTURER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeviceManufacturer() {
    return deviceManufacturer;
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE_MANUFACTURER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceManufacturer(@jakarta.annotation.Nullable String deviceManufacturer) {
    this.deviceManufacturer = deviceManufacturer;
  }

  public DeviceDetails deviceModel(@jakarta.annotation.Nullable String deviceModel) {
    this.deviceModel = deviceModel;
    return this;
  }

  /**
   * Raw device model identifier, as reported by the mobile OS.
   * @return deviceModel
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDeviceModel() {
    return deviceModel;
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceModel(@jakarta.annotation.Nullable String deviceModel) {
    this.deviceModel = deviceModel;
  }

  public DeviceDetails osVersion(@jakarta.annotation.Nullable String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Mobile operating system version. Component count is not fixed and must not be assumed by consumers: iOS always reports `major.minor.patch` (e.g. `17.4.1`), while Android's precision varies by OS era and which raw signal resolved it — `major` only (`9`, `13`) since Android 10 dropped point releases, `major.minor` (`16.1`) from Android 16 (API 36+) reintroducing a minor component, or a genuine `major.minor.patch` (`8.1.0`) on pre-Android 10 devices that shipped real point releases. Never a fabricated/zero-padded component.
   * @return osVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OS_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOsVersion() {
    return osVersion;
  }

  @JsonProperty(value = JSON_PROPERTY_OS_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsVersion(@jakarta.annotation.Nullable String osVersion) {
    this.osVersion = osVersion;
  }

  /**
   * Return true if this DeviceDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceDetails deviceDetails = (DeviceDetails) o;
    return Objects.equals(this.deviceManufacturer, deviceDetails.deviceManufacturer)
        && Objects.equals(this.deviceModel, deviceDetails.deviceModel)
        && Objects.equals(this.osVersion, deviceDetails.osVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceManufacturer, deviceModel, osVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceDetails {\n");
    sb.append("    deviceManufacturer: ").append(toIndentedString(deviceManufacturer)).append("\n");
    sb.append("    deviceModel: ").append(toIndentedString(deviceModel)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
