/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * HTTP request metadata (including the HTTP method, headers and IP address) sent by you (your server) to the Fingerprint API for IP and bot analysis. To improve accuracy, retain as much of the original semantics of the HTTP request as possible. For example, preserve the order of the request headers and their capitalization. At least one of `ipv4_address` or `ipv6_address` must be provided; a request with neither is rejected with a `400` error. If both IPv4 and IPv6 are provided, IP intelligence will be provided for each address. If an IPv4-mapped IPv6 address is provided in the `ipv6_address` request property, the IP intelligence will be provided in the `ipv4_address` property of the response.
 */
@JsonPropertyOrder({
  EdgeRequest.JSON_PROPERTY_HEADERS,
  EdgeRequest.JSON_PROPERTY_METHOD,
  EdgeRequest.JSON_PROPERTY_URL,
  EdgeRequest.JSON_PROPERTY_IPV4_ADDRESS,
  EdgeRequest.JSON_PROPERTY_IPV6_ADDRESS,
  EdgeRequest.JSON_PROPERTY_LINKED_ID,
  EdgeRequest.JSON_PROPERTY_TAGS
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.24.0")
public class EdgeRequest {
  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nonnull private List<EdgeRequestHeadersInner> headers = new ArrayList<>();

  public static final String JSON_PROPERTY_METHOD = "method";
  @jakarta.annotation.Nonnull private String method;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull private URI url;

  public static final String JSON_PROPERTY_IPV4_ADDRESS = "ipv4_address";
  @jakarta.annotation.Nullable private String ipv4Address;

  public static final String JSON_PROPERTY_IPV6_ADDRESS = "ipv6_address";
  @jakarta.annotation.Nullable private String ipv6Address;

  public static final String JSON_PROPERTY_LINKED_ID = "linked_id";
  @jakarta.annotation.Nullable private String linkedId;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @jakarta.annotation.Nullable private Map<String, Object> tags = new HashMap<>();

  public EdgeRequest() {}

  public EdgeRequest headers(@jakarta.annotation.Nonnull List<EdgeRequestHeadersInner> headers) {
    this.headers = headers;
    return this;
  }

  public EdgeRequest addHeadersItem(EdgeRequestHeadersInner headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

  /**
   * Ordered header entries from the request made to your server. Each entry represents one header line. If one header name appears as multiple lines, send each as a separate item in the array.  Headers that contain authentication or session data must still be included, but with their value set to an empty string. This includes headers like `Authorization` and `Cookie`, but may contain more depending on your specific project, for instance `Proxy-Authenticate` or `X-Api-Key`. Omitting the headers entirely changes the shape of the request and can affect detection. Never forward the real secret values.  Whenever possible, we recommend preserving header order and capitalization to provide the best accuracy, however it’s not a strict requirement if your runtime does not maintain http header order or canonicalizes header names.
   * @return headers
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<EdgeRequestHeadersInner> getHeaders() {
    return headers;
  }

  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeaders(@jakarta.annotation.Nonnull List<EdgeRequestHeadersInner> headers) {
    this.headers = headers;
  }

  public EdgeRequest method(@jakarta.annotation.Nonnull String method) {
    this.method = method;
    return this;
  }

  /**
   * The original HTTP method of the request. If supported in your runtime, preserve the original casing.
   * @return method
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMethod() {
    return method;
  }

  @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMethod(@jakarta.annotation.Nonnull String method) {
    this.method = method;
  }

  public EdgeRequest url(@jakarta.annotation.Nonnull URI url) {
    this.url = url;
    return this;
  }

  /**
   * Absolute URL of the request, without a \\#fragment suffix. Only HTTP and HTTPS schemes are supported.
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getUrl() {
    return url;
  }

  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull URI url) {
    this.url = url;
  }

  public EdgeRequest ipv4Address(@jakarta.annotation.Nullable String ipv4Address) {
    this.ipv4Address = ipv4Address;
    return this;
  }

  /**
   * Client IPv4 address observed by your server.
   * @return ipv4Address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IPV4_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIpv4Address() {
    return ipv4Address;
  }

  @JsonProperty(value = JSON_PROPERTY_IPV4_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpv4Address(@jakarta.annotation.Nullable String ipv4Address) {
    this.ipv4Address = ipv4Address;
  }

  public EdgeRequest ipv6Address(@jakarta.annotation.Nullable String ipv6Address) {
    this.ipv6Address = ipv6Address;
    return this;
  }

  /**
   * Client IPv6 address observed by your server.
   * @return ipv6Address
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IPV6_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIpv6Address() {
    return ipv6Address;
  }

  @JsonProperty(value = JSON_PROPERTY_IPV6_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpv6Address(@jakarta.annotation.Nullable String ipv6Address) {
    this.ipv6Address = ipv6Address;
  }

  public EdgeRequest linkedId(@jakarta.annotation.Nullable String linkedId) {
    this.linkedId = linkedId;
    return this;
  }

  /**
   * A customer-provided id that was sent with the request.
   * @return linkedId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLinkedId() {
    return linkedId;
  }

  @JsonProperty(value = JSON_PROPERTY_LINKED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkedId(@jakarta.annotation.Nullable String linkedId) {
    this.linkedId = linkedId;
  }

  public EdgeRequest tags(@jakarta.annotation.Nullable Map<String, Object> tags) {
    this.tags = tags;
    return this;
  }

  public EdgeRequest putTagsItem(String key, Object tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

  /**
   * A customer-provided value or an object that was sent with the identification request or updated later.
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getTags() {
    return tags;
  }

  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@jakarta.annotation.Nullable Map<String, Object> tags) {
    this.tags = tags;
  }

  /**
   * Return true if this EdgeRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdgeRequest edgeRequest = (EdgeRequest) o;
    return Objects.equals(this.headers, edgeRequest.headers)
        && Objects.equals(this.method, edgeRequest.method)
        && Objects.equals(this.url, edgeRequest.url)
        && Objects.equals(this.ipv4Address, edgeRequest.ipv4Address)
        && Objects.equals(this.ipv6Address, edgeRequest.ipv6Address)
        && Objects.equals(this.linkedId, edgeRequest.linkedId)
        && Objects.equals(this.tags, edgeRequest.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headers, method, url, ipv4Address, ipv6Address, linkedId, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdgeRequest {\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    ipv4Address: ").append(toIndentedString(ipv4Address)).append("\n");
    sb.append("    ipv6Address: ").append(toIndentedString(ipv6Address)).append("\n");
    sb.append("    linkedId: ").append(toIndentedString(linkedId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
