/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * Bounding box metrics describing how the emoji glyph renders.
 */
@JsonPropertyOrder({
  Emoji.JSON_PROPERTY_FONT,
  Emoji.JSON_PROPERTY_WIDTH,
  Emoji.JSON_PROPERTY_HEIGHT,
  Emoji.JSON_PROPERTY_TOP,
  Emoji.JSON_PROPERTY_BOTTOM,
  Emoji.JSON_PROPERTY_LEFT,
  Emoji.JSON_PROPERTY_RIGHT,
  Emoji.JSON_PROPERTY_X,
  Emoji.JSON_PROPERTY_Y
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.16.0")
public class Emoji {
  public static final String JSON_PROPERTY_FONT = "font";
  @jakarta.annotation.Nullable private String font;

  public static final String JSON_PROPERTY_WIDTH = "width";
  @jakarta.annotation.Nullable private Double width;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @jakarta.annotation.Nullable private Double height;

  public static final String JSON_PROPERTY_TOP = "top";
  @jakarta.annotation.Nullable private Double top;

  public static final String JSON_PROPERTY_BOTTOM = "bottom";
  @jakarta.annotation.Nullable private Double bottom;

  public static final String JSON_PROPERTY_LEFT = "left";
  @jakarta.annotation.Nullable private Double left;

  public static final String JSON_PROPERTY_RIGHT = "right";
  @jakarta.annotation.Nullable private Double right;

  public static final String JSON_PROPERTY_X = "x";
  @jakarta.annotation.Nullable private Double x;

  public static final String JSON_PROPERTY_Y = "y";
  @jakarta.annotation.Nullable private Double y;

  public Emoji() {}

  public Emoji font(@jakarta.annotation.Nullable String font) {
    this.font = font;
    return this;
  }

  /**
   * Font family reported by the browser when drawing the emoji.
   * @return font
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFont() {
    return font;
  }

  @JsonProperty(value = JSON_PROPERTY_FONT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFont(@jakarta.annotation.Nullable String font) {
    this.font = font;
  }

  public Emoji width(@jakarta.annotation.Nullable Double width) {
    this.width = width;
    return this;
  }

  /**
   * Get width
   * @return width
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getWidth() {
    return width;
  }

  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(@jakarta.annotation.Nullable Double width) {
    this.width = width;
  }

  public Emoji height(@jakarta.annotation.Nullable Double height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getHeight() {
    return height;
  }

  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(@jakarta.annotation.Nullable Double height) {
    this.height = height;
  }

  public Emoji top(@jakarta.annotation.Nullable Double top) {
    this.top = top;
    return this;
  }

  /**
   * Get top
   * @return top
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTop() {
    return top;
  }

  @JsonProperty(value = JSON_PROPERTY_TOP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTop(@jakarta.annotation.Nullable Double top) {
    this.top = top;
  }

  public Emoji bottom(@jakarta.annotation.Nullable Double bottom) {
    this.bottom = bottom;
    return this;
  }

  /**
   * Get bottom
   * @return bottom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOTTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getBottom() {
    return bottom;
  }

  @JsonProperty(value = JSON_PROPERTY_BOTTOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBottom(@jakarta.annotation.Nullable Double bottom) {
    this.bottom = bottom;
  }

  public Emoji left(@jakarta.annotation.Nullable Double left) {
    this.left = left;
    return this;
  }

  /**
   * Get left
   * @return left
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEFT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getLeft() {
    return left;
  }

  @JsonProperty(value = JSON_PROPERTY_LEFT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeft(@jakarta.annotation.Nullable Double left) {
    this.left = left;
  }

  public Emoji right(@jakarta.annotation.Nullable Double right) {
    this.right = right;
    return this;
  }

  /**
   * Get right
   * @return right
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getRight() {
    return right;
  }

  @JsonProperty(value = JSON_PROPERTY_RIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRight(@jakarta.annotation.Nullable Double right) {
    this.right = right;
  }

  public Emoji x(@jakarta.annotation.Nullable Double x) {
    this.x = x;
    return this;
  }

  /**
   * Get x
   * @return x
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_X, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getX() {
    return x;
  }

  @JsonProperty(value = JSON_PROPERTY_X, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setX(@jakarta.annotation.Nullable Double x) {
    this.x = x;
  }

  public Emoji y(@jakarta.annotation.Nullable Double y) {
    this.y = y;
    return this;
  }

  /**
   * Get y
   * @return y
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_Y, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getY() {
    return y;
  }

  @JsonProperty(value = JSON_PROPERTY_Y, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setY(@jakarta.annotation.Nullable Double y) {
    this.y = y;
  }

  /**
   * Return true if this Emoji object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Emoji emoji = (Emoji) o;
    return Objects.equals(this.font, emoji.font)
        && Objects.equals(this.width, emoji.width)
        && Objects.equals(this.height, emoji.height)
        && Objects.equals(this.top, emoji.top)
        && Objects.equals(this.bottom, emoji.bottom)
        && Objects.equals(this.left, emoji.left)
        && Objects.equals(this.right, emoji.right)
        && Objects.equals(this.x, emoji.x)
        && Objects.equals(this.y, emoji.y);
  }

  @Override
  public int hashCode() {
    return Objects.hash(font, width, height, top, bottom, left, right, x, y);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emoji {\n");
    sb.append("    font: ").append(toIndentedString(font)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    bottom: ").append(toIndentedString(bottom)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
