/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.24.0")
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "source",
    defaultImpl = Event.UnknownEvent.class,
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = EventDevice.class, name = "device"),
  @JsonSubTypes.Type(value = EventEdge.class, name = "edge")
})
/**
 * SPIKE INTER-2457 — BREAKING CHANGE. DO NOT SHIP.
 * Event used to be a class with getIdentification(). It is now an interface
 * (useOneOfInterfaces: true) with no getIdentification(). Existing callers
 * of api.getEvent(id).getIdentification() fail to compile. Cast to EventDevice
 * after checking getSource(), or this is a binary-incompatible major version.
 */
public interface Event {

  static final String JSON_PROPERTY_EVENT_ID = "event_id";

  static final String JSON_PROPERTY_TIMESTAMP = "timestamp";

  static final String JSON_PROPERTY_IP_INFO = "ip_info";

  static final String JSON_PROPERTY_SOURCE = "source";

  /**
   * Unique identifier of the user&#39;s request. The first portion of the event_id is a unix epoch milliseconds timestamp.
   * @return eventId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  String getEventId();

  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  void setEventId(@jakarta.annotation.Nonnull String eventId);

  Event eventId(@jakarta.annotation.Nonnull String eventId);

  /**
   * Timestamp of the event with millisecond precision in Unix time.
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  Long getTimestamp();

  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  void setTimestamp(@jakarta.annotation.Nonnull Long timestamp);

  Event timestamp(@jakarta.annotation.Nonnull Long timestamp);

  /**
   * Get ipInfo
   * @return ipInfo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  IPInfo getIpInfo();

  @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  void setIpInfo(@jakarta.annotation.Nonnull IPInfo ipInfo);

  Event ipInfo(@jakarta.annotation.Nonnull IPInfo ipInfo);

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  EventSource getSource();

  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  void setSource(@jakarta.annotation.Nonnull EventSource source);

  Event source(@jakarta.annotation.Nonnull EventSource source);

  public static final class UnknownEvent implements Event {

    public static final String JSON_PROPERTY_EVENT_ID = "event_id";
    @jakarta.annotation.Nonnull private String eventId;

    public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
    @jakarta.annotation.Nonnull private Long timestamp;

    public static final String JSON_PROPERTY_IP_INFO = "ip_info";
    @jakarta.annotation.Nonnull private IPInfo ipInfo;

    public static final String JSON_PROPERTY_SOURCE = "source";
    // The discriminator does not have Nullability-annotation since it is added during serialization
    // by the @JsonTypeName annotation
    private EventSource source;

    public UnknownEvent() {}

    public Event eventId(@jakarta.annotation.Nonnull String eventId) {

      this.eventId = eventId;
      return this;
    }

    /**
     * Unique identifier of the user&#39;s request. The first portion of the event_id is a unix epoch milliseconds timestamp.
     * @return eventId
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getEventId() {
      return eventId;
    }

    @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEventId(@jakarta.annotation.Nonnull String eventId) {
      this.eventId = eventId;
    }

    public Event timestamp(@jakarta.annotation.Nonnull Long timestamp) {

      this.timestamp = timestamp;
      return this;
    }

    /**
     * Timestamp of the event with millisecond precision in Unix time.
     * @return timestamp
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Long getTimestamp() {
      return timestamp;
    }

    @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTimestamp(@jakarta.annotation.Nonnull Long timestamp) {
      this.timestamp = timestamp;
    }

    public Event ipInfo(@jakarta.annotation.Nonnull IPInfo ipInfo) {

      this.ipInfo = ipInfo;
      return this;
    }

    /**
     * Get ipInfo
     * @return ipInfo
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public IPInfo getIpInfo() {
      return ipInfo;
    }

    @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setIpInfo(@jakarta.annotation.Nonnull IPInfo ipInfo) {
      this.ipInfo = ipInfo;
    }

    public Event source(@jakarta.annotation.Nonnull EventSource source) {

      this.source = source;
      return this;
    }

    /**
     * Get source
     * @return source
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public EventSource getSource() {
      return source;
    }

    @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSource(@jakarta.annotation.Nonnull EventSource source) {
      this.source = source;
    }
  }
}
