/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.v4.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fingerprint.v4.model.RuleActionHeaderField;
import com.fingerprint.v4.model.RuleActionType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.v4.sdk.JSON;


/**
 * Informs the client the request should be blocked using the response described by this rule action.
 */
@JsonPropertyOrder({
  EventRuleActionBlock.JSON_PROPERTY_RULESET_ID,
  EventRuleActionBlock.JSON_PROPERTY_RULE_ID,
  EventRuleActionBlock.JSON_PROPERTY_RULE_EXPRESSION,
  EventRuleActionBlock.JSON_PROPERTY_TYPE,
  EventRuleActionBlock.JSON_PROPERTY_STATUS_CODE,
  EventRuleActionBlock.JSON_PROPERTY_HEADERS,
  EventRuleActionBlock.JSON_PROPERTY_BODY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class EventRuleActionBlock implements EventRuleAction {
  public static final String JSON_PROPERTY_RULESET_ID = "ruleset_id";
  @jakarta.annotation.Nonnull
  private String rulesetId;

  public static final String JSON_PROPERTY_RULE_ID = "rule_id";
  @jakarta.annotation.Nullable
  private String ruleId;

  public static final String JSON_PROPERTY_RULE_EXPRESSION = "rule_expression";
  @jakarta.annotation.Nullable
  private String ruleExpression;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private RuleActionType type;

  public static final String JSON_PROPERTY_STATUS_CODE = "status_code";
  @jakarta.annotation.Nullable
  private Integer statusCode;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nullable
  private List<RuleActionHeaderField> headers = new ArrayList<>();

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nullable
  private String body;

  public EventRuleActionBlock() { 
  }

  public EventRuleActionBlock rulesetId(@jakarta.annotation.Nonnull String rulesetId) {
    this.rulesetId = rulesetId;
    return this;
  }

  /**
   * The ID of the evaluated ruleset.
   * @return rulesetId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRulesetId() {
    return rulesetId;
  }


  @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRulesetId(@jakarta.annotation.Nonnull String rulesetId) {
    this.rulesetId = rulesetId;
  }


  public EventRuleActionBlock ruleId(@jakarta.annotation.Nullable String ruleId) {
    this.ruleId = ruleId;
    return this;
  }

  /**
   * The ID of the rule that matched the identification event.
   * @return ruleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRuleId() {
    return ruleId;
  }


  @JsonProperty(value = JSON_PROPERTY_RULE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuleId(@jakarta.annotation.Nullable String ruleId) {
    this.ruleId = ruleId;
  }


  public EventRuleActionBlock ruleExpression(@jakarta.annotation.Nullable String ruleExpression) {
    this.ruleExpression = ruleExpression;
    return this;
  }

  /**
   * The expression of the rule that matched the identification event.
   * @return ruleExpression
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULE_EXPRESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRuleExpression() {
    return ruleExpression;
  }


  @JsonProperty(value = JSON_PROPERTY_RULE_EXPRESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuleExpression(@jakarta.annotation.Nullable String ruleExpression) {
    this.ruleExpression = ruleExpression;
  }


  public EventRuleActionBlock type(@jakarta.annotation.Nonnull RuleActionType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RuleActionType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull RuleActionType type) {
    this.type = type;
  }


  public EventRuleActionBlock statusCode(@jakarta.annotation.Nullable Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * A valid HTTP status code.
   * @return statusCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStatusCode() {
    return statusCode;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusCode(@jakarta.annotation.Nullable Integer statusCode) {
    this.statusCode = statusCode;
  }


  public EventRuleActionBlock headers(@jakarta.annotation.Nullable List<RuleActionHeaderField> headers) {
    this.headers = headers;
    return this;
  }

  public EventRuleActionBlock addHeadersItem(RuleActionHeaderField headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

  /**
   * A list of headers to send.
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RuleActionHeaderField> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@jakarta.annotation.Nullable List<RuleActionHeaderField> headers) {
    this.headers = headers;
  }


  public EventRuleActionBlock body(@jakarta.annotation.Nullable String body) {
    this.body = body;
    return this;
  }

  /**
   * The response body to send to the client.
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@jakarta.annotation.Nullable String body) {
    this.body = body;
  }


  /**
   * Return true if this EventRuleActionBlock object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventRuleActionBlock eventRuleActionBlock = (EventRuleActionBlock) o;
    return Objects.equals(this.rulesetId, eventRuleActionBlock.rulesetId) &&
        Objects.equals(this.ruleId, eventRuleActionBlock.ruleId) &&
        Objects.equals(this.ruleExpression, eventRuleActionBlock.ruleExpression) &&
        Objects.equals(this.type, eventRuleActionBlock.type) &&
        Objects.equals(this.statusCode, eventRuleActionBlock.statusCode) &&
        Objects.equals(this.headers, eventRuleActionBlock.headers) &&
        Objects.equals(this.body, eventRuleActionBlock.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rulesetId, ruleId, ruleExpression, type, statusCode, headers, body);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventRuleActionBlock {\n");
    sb.append("    rulesetId: ").append(toIndentedString(rulesetId)).append("\n");
    sb.append("    ruleId: ").append(toIndentedString(ruleId)).append("\n");
    sb.append("    ruleExpression: ").append(toIndentedString(ruleExpression)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

