/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * IP and bot analysis for an event generated by the Automation Intelligence API (`/edge` endpoint). No client-side collection agent is involved, so Identification (`visitor_id`) and device-telemetry-derived Smart Signals are not available.
 */
@JsonPropertyOrder({
  EventEdge.JSON_PROPERTY_EVENT_ID,
  EventEdge.JSON_PROPERTY_TIMESTAMP,
  EventEdge.JSON_PROPERTY_LINKED_ID,
  EventEdge.JSON_PROPERTY_TAGS,
  EventEdge.JSON_PROPERTY_URL,
  EventEdge.JSON_PROPERTY_BOT_INFO,
  EventEdge.JSON_PROPERTY_IP_INFO,
  EventEdge.JSON_PROPERTY_PROXY,
  EventEdge.JSON_PROPERTY_PROXY_CONFIDENCE,
  EventEdge.JSON_PROPERTY_PROXY_DETAILS,
  EventEdge.JSON_PROPERTY_VPN,
  EventEdge.JSON_PROPERTY_VPN_CONFIDENCE,
  EventEdge.JSON_PROPERTY_VPN_METHODS,
  EventEdge.JSON_PROPERTY_SOURCE
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.24.0")
public class EventEdge implements Event {
  public static final String JSON_PROPERTY_EVENT_ID = "event_id";
  @jakarta.annotation.Nonnull private String eventId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull private Long timestamp;

  public static final String JSON_PROPERTY_LINKED_ID = "linked_id";
  @jakarta.annotation.Nullable private String linkedId;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @jakarta.annotation.Nullable private Map<String, Object> tags = new HashMap<>();

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable private String url;

  public static final String JSON_PROPERTY_BOT_INFO = "bot_info";
  @jakarta.annotation.Nullable private BotInfo botInfo;

  public static final String JSON_PROPERTY_IP_INFO = "ip_info";
  @jakarta.annotation.Nonnull private IPInfo ipInfo;

  public static final String JSON_PROPERTY_PROXY = "proxy";
  @jakarta.annotation.Nullable private Boolean proxy;

  public static final String JSON_PROPERTY_PROXY_CONFIDENCE = "proxy_confidence";
  @jakarta.annotation.Nullable private ProxyConfidence proxyConfidence;

  public static final String JSON_PROPERTY_PROXY_DETAILS = "proxy_details";
  @jakarta.annotation.Nullable private ProxyDetails proxyDetails;

  public static final String JSON_PROPERTY_VPN = "vpn";
  @jakarta.annotation.Nullable private Boolean vpn;

  public static final String JSON_PROPERTY_VPN_CONFIDENCE = "vpn_confidence";
  @jakarta.annotation.Nullable private VpnConfidence vpnConfidence;

  public static final String JSON_PROPERTY_VPN_METHODS = "vpn_methods";
  @jakarta.annotation.Nullable private VpnMethods vpnMethods;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nonnull private EventSource source;

  public EventEdge() {}

  public EventEdge eventId(@jakarta.annotation.Nonnull String eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp.
   * @return eventId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEventId() {
    return eventId;
  }

  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventId(@jakarta.annotation.Nonnull String eventId) {
    this.eventId = eventId;
  }

  public EventEdge timestamp(@jakarta.annotation.Nonnull Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Timestamp of the event with millisecond precision in Unix time.
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getTimestamp() {
    return timestamp;
  }

  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull Long timestamp) {
    this.timestamp = timestamp;
  }

  public EventEdge linkedId(@jakarta.annotation.Nullable String linkedId) {
    this.linkedId = linkedId;
    return this;
  }

  /**
   * A customer-provided id that was sent with the request.
   * @return linkedId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLinkedId() {
    return linkedId;
  }

  @JsonProperty(value = JSON_PROPERTY_LINKED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkedId(@jakarta.annotation.Nullable String linkedId) {
    this.linkedId = linkedId;
  }

  public EventEdge tags(@jakarta.annotation.Nullable Map<String, Object> tags) {
    this.tags = tags;
    return this;
  }

  public EventEdge putTagsItem(String key, Object tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

  /**
   * A customer-provided value or an object that was sent with the identification request or updated later.
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getTags() {
    return tags;
  }

  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@jakarta.annotation.Nullable Map<String, Object> tags) {
    this.tags = tags;
  }

  public EventEdge url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Page URL from which the request was sent.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }

  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }

  public EventEdge botInfo(@jakarta.annotation.Nullable BotInfo botInfo) {
    this.botInfo = botInfo;
    return this;
  }

  /**
   * Get botInfo
   * @return botInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BotInfo getBotInfo() {
    return botInfo;
  }

  @JsonProperty(value = JSON_PROPERTY_BOT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBotInfo(@jakarta.annotation.Nullable BotInfo botInfo) {
    this.botInfo = botInfo;
  }

  public EventEdge ipInfo(@jakarta.annotation.Nonnull IPInfo ipInfo) {
    this.ipInfo = ipInfo;
    return this;
  }

  /**
   * Get ipInfo
   * @return ipInfo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public IPInfo getIpInfo() {
    return ipInfo;
  }

  @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIpInfo(@jakarta.annotation.Nonnull IPInfo ipInfo) {
    this.ipInfo = ipInfo;
  }

  public EventEdge proxy(@jakarta.annotation.Nullable Boolean proxy) {
    this.proxy = proxy;
    return this;
  }

  /**
   * IP address was used by a public proxy provider or belonged to a known recent residential proxy
   * @return proxy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getProxy() {
    return proxy;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxy(@jakarta.annotation.Nullable Boolean proxy) {
    this.proxy = proxy;
  }

  public EventEdge proxyConfidence(@jakarta.annotation.Nullable ProxyConfidence proxyConfidence) {
    this.proxyConfidence = proxyConfidence;
    return this;
  }

  /**
   * Get proxyConfidence
   * @return proxyConfidence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyConfidence getProxyConfidence() {
    return proxyConfidence;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxyConfidence(@jakarta.annotation.Nullable ProxyConfidence proxyConfidence) {
    this.proxyConfidence = proxyConfidence;
  }

  public EventEdge proxyDetails(@jakarta.annotation.Nullable ProxyDetails proxyDetails) {
    this.proxyDetails = proxyDetails;
    return this;
  }

  /**
   * Get proxyDetails
   * @return proxyDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyDetails getProxyDetails() {
    return proxyDetails;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxyDetails(@jakarta.annotation.Nullable ProxyDetails proxyDetails) {
    this.proxyDetails = proxyDetails;
  }

  public EventEdge vpn(@jakarta.annotation.Nullable Boolean vpn) {
    this.vpn = vpn;
    return this;
  }

  /**
   * VPN or other anonymizing service has been used when sending the request.
   * @return vpn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getVpn() {
    return vpn;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpn(@jakarta.annotation.Nullable Boolean vpn) {
    this.vpn = vpn;
  }

  public EventEdge vpnConfidence(@jakarta.annotation.Nullable VpnConfidence vpnConfidence) {
    this.vpnConfidence = vpnConfidence;
    return this;
  }

  /**
   * Get vpnConfidence
   * @return vpnConfidence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VpnConfidence getVpnConfidence() {
    return vpnConfidence;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnConfidence(@jakarta.annotation.Nullable VpnConfidence vpnConfidence) {
    this.vpnConfidence = vpnConfidence;
  }

  public EventEdge vpnMethods(@jakarta.annotation.Nullable VpnMethods vpnMethods) {
    this.vpnMethods = vpnMethods;
    return this;
  }

  /**
   * Get vpnMethods
   * @return vpnMethods
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_METHODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VpnMethods getVpnMethods() {
    return vpnMethods;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_METHODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnMethods(@jakarta.annotation.Nullable VpnMethods vpnMethods) {
    this.vpnMethods = vpnMethods;
  }

  public EventEdge source(@jakarta.annotation.Nonnull EventSource source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventSource getSource() {
    return source;
  }

  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@jakarta.annotation.Nonnull EventSource source) {
    this.source = source;
  }

  /**
   * Return true if this EventEdge object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventEdge eventEdge = (EventEdge) o;
    return Objects.equals(this.eventId, eventEdge.eventId)
        && Objects.equals(this.timestamp, eventEdge.timestamp)
        && Objects.equals(this.linkedId, eventEdge.linkedId)
        && Objects.equals(this.tags, eventEdge.tags)
        && Objects.equals(this.url, eventEdge.url)
        && Objects.equals(this.botInfo, eventEdge.botInfo)
        && Objects.equals(this.ipInfo, eventEdge.ipInfo)
        && Objects.equals(this.proxy, eventEdge.proxy)
        && Objects.equals(this.proxyConfidence, eventEdge.proxyConfidence)
        && Objects.equals(this.proxyDetails, eventEdge.proxyDetails)
        && Objects.equals(this.vpn, eventEdge.vpn)
        && Objects.equals(this.vpnConfidence, eventEdge.vpnConfidence)
        && Objects.equals(this.vpnMethods, eventEdge.vpnMethods)
        && Objects.equals(this.source, eventEdge.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        eventId,
        timestamp,
        linkedId,
        tags,
        url,
        botInfo,
        ipInfo,
        proxy,
        proxyConfidence,
        proxyDetails,
        vpn,
        vpnConfidence,
        vpnMethods,
        source);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventEdge {\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    linkedId: ").append(toIndentedString(linkedId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    botInfo: ").append(toIndentedString(botInfo)).append("\n");
    sb.append("    ipInfo: ").append(toIndentedString(ipInfo)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("    proxyConfidence: ").append(toIndentedString(proxyConfidence)).append("\n");
    sb.append("    proxyDetails: ").append(toIndentedString(proxyDetails)).append("\n");
    sb.append("    vpn: ").append(toIndentedString(vpn)).append("\n");
    sb.append("    vpnConfidence: ").append(toIndentedString(vpnConfidence)).append("\n");
    sb.append("    vpnMethods: ").append(toIndentedString(vpnMethods)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
