/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.16.0")
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
    defaultImpl = EventRuleAction.UnknownEventRuleAction.class,
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = EventRuleActionAllow.class, name = "allow"),
  @JsonSubTypes.Type(value = EventRuleActionBlock.class, name = "block")
})
public interface EventRuleAction {

  static final String JSON_PROPERTY_RULESET_ID = "ruleset_id";

  static final String JSON_PROPERTY_TYPE = "type";

  /**
   * The ID of the evaluated ruleset.
   * @return rulesetId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  String getRulesetId();

  @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  void setRulesetId(@jakarta.annotation.Nonnull String rulesetId);

  EventRuleAction rulesetId(@jakarta.annotation.Nonnull String rulesetId);

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  RuleActionType getType();

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  void setType(@jakarta.annotation.Nonnull RuleActionType type);

  EventRuleAction type(@jakarta.annotation.Nonnull RuleActionType type);

  public static final class UnknownEventRuleAction implements EventRuleAction {

    public static final String JSON_PROPERTY_RULESET_ID = "ruleset_id";
    @jakarta.annotation.Nonnull private String rulesetId;

    public static final String JSON_PROPERTY_TYPE = "type";
    // The discriminator does not have Nullability-annotation since it is added during serialization
    // by the @JsonTypeName annotation
    private RuleActionType type;

    public UnknownEventRuleAction() {}

    public EventRuleAction rulesetId(@jakarta.annotation.Nonnull String rulesetId) {

      this.rulesetId = rulesetId;
      return this;
    }

    /**
     * The ID of the evaluated ruleset.
     * @return rulesetId
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getRulesetId() {
      return rulesetId;
    }

    @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setRulesetId(@jakarta.annotation.Nonnull String rulesetId) {
      this.rulesetId = rulesetId;
    }

    public EventRuleAction type(@jakarta.annotation.Nonnull RuleActionType type) {

      this.type = type;
      return this;
    }

    /**
     * Get type
     * @return type
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public RuleActionType getType() {
      return type;
    }

    @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(@jakarta.annotation.Nonnull RuleActionType type) {
      this.type = type;
    }
  }
}
