/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. The API also supports collection of Automation Intelligence for requests to your server in edge, pre-origin, or middleware contexts.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Contains results from Fingerprint Identification and Smart Signals derived from client-side device telemetry. Consult the [Smart Signals reference](https://docs.fingerprint.com/docs/smart-signals-reference) for more details.
 */
@JsonPropertyOrder({
  EventDevice.JSON_PROPERTY_EVENT_ID,
  EventDevice.JSON_PROPERTY_TIMESTAMP,
  EventDevice.JSON_PROPERTY_LINKED_ID,
  EventDevice.JSON_PROPERTY_TAGS,
  EventDevice.JSON_PROPERTY_URL,
  EventDevice.JSON_PROPERTY_BOT_INFO,
  EventDevice.JSON_PROPERTY_IP_INFO,
  EventDevice.JSON_PROPERTY_PROXY,
  EventDevice.JSON_PROPERTY_PROXY_CONFIDENCE,
  EventDevice.JSON_PROPERTY_PROXY_DETAILS,
  EventDevice.JSON_PROPERTY_VPN,
  EventDevice.JSON_PROPERTY_VPN_CONFIDENCE,
  EventDevice.JSON_PROPERTY_VPN_METHODS,
  EventDevice.JSON_PROPERTY_SOURCE,
  EventDevice.JSON_PROPERTY_INCREMENTAL_IDENTIFICATION_STATUS,
  EventDevice.JSON_PROPERTY_ENVIRONMENT_ID,
  EventDevice.JSON_PROPERTY_SUSPECT,
  EventDevice.JSON_PROPERTY_SDK,
  EventDevice.JSON_PROPERTY_REPLAYED,
  EventDevice.JSON_PROPERTY_IDENTIFICATION,
  EventDevice.JSON_PROPERTY_SUPPLEMENTARY_ID_HIGH_RECALL,
  EventDevice.JSON_PROPERTY_BUNDLE_ID,
  EventDevice.JSON_PROPERTY_PACKAGE_NAME,
  EventDevice.JSON_PROPERTY_IP_ADDRESS,
  EventDevice.JSON_PROPERTY_USER_AGENT,
  EventDevice.JSON_PROPERTY_DEVICE,
  EventDevice.JSON_PROPERTY_OS,
  EventDevice.JSON_PROPERTY_OS_VERSION,
  EventDevice.JSON_PROPERTY_CLIENT_REFERRER,
  EventDevice.JSON_PROPERTY_BROWSER_DETAILS,
  EventDevice.JSON_PROPERTY_PROXIMITY,
  EventDevice.JSON_PROPERTY_ACTIVE_CALL,
  EventDevice.JSON_PROPERTY_BOT,
  EventDevice.JSON_PROPERTY_BOT_TYPE,
  EventDevice.JSON_PROPERTY_CLONED_APP,
  EventDevice.JSON_PROPERTY_DEVELOPER_TOOLS,
  EventDevice.JSON_PROPERTY_EMULATOR,
  EventDevice.JSON_PROPERTY_FACTORY_RESET_TIMESTAMP,
  EventDevice.JSON_PROPERTY_FRIDA,
  EventDevice.JSON_PROPERTY_IP_BLOCKLIST,
  EventDevice.JSON_PROPERTY_PROXY_ML_SCORE,
  EventDevice.JSON_PROPERTY_INCOGNITO,
  EventDevice.JSON_PROPERTY_JAILBROKEN,
  EventDevice.JSON_PROPERTY_LOCATION_SPOOFING,
  EventDevice.JSON_PROPERTY_MITM_ATTACK,
  EventDevice.JSON_PROPERTY_PRIVACY_SETTINGS,
  EventDevice.JSON_PROPERTY_ROOT_APPS,
  EventDevice.JSON_PROPERTY_RULE_ACTION,
  EventDevice.JSON_PROPERTY_SIMULATOR,
  EventDevice.JSON_PROPERTY_SUSPECT_SCORE,
  EventDevice.JSON_PROPERTY_TAMPERING,
  EventDevice.JSON_PROPERTY_TAMPERING_CONFIDENCE,
  EventDevice.JSON_PROPERTY_TAMPERING_ML_SCORE,
  EventDevice.JSON_PROPERTY_TAMPERING_DETAILS,
  EventDevice.JSON_PROPERTY_VELOCITY,
  EventDevice.JSON_PROPERTY_VIRTUAL_MACHINE,
  EventDevice.JSON_PROPERTY_VIRTUAL_MACHINE_ML_SCORE,
  EventDevice.JSON_PROPERTY_VPN_ML_SCORE,
  EventDevice.JSON_PROPERTY_VPN_ORIGIN_TIMEZONE,
  EventDevice.JSON_PROPERTY_VPN_ORIGIN_COUNTRY,
  EventDevice.JSON_PROPERTY_HIGH_ACTIVITY_DEVICE,
  EventDevice.JSON_PROPERTY_RARE_DEVICE,
  EventDevice.JSON_PROPERTY_RARE_DEVICE_PERCENTILE_BUCKET,
  EventDevice.JSON_PROPERTY_RAW_DEVICE_ATTRIBUTES,
  EventDevice.JSON_PROPERTY_LABELS
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.24.0")
public class EventDevice implements Event {
  public static final String JSON_PROPERTY_EVENT_ID = "event_id";
  @jakarta.annotation.Nonnull private String eventId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nonnull private Long timestamp;

  public static final String JSON_PROPERTY_LINKED_ID = "linked_id";
  @jakarta.annotation.Nullable private String linkedId;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @jakarta.annotation.Nullable private Map<String, Object> tags = new HashMap<>();

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable private String url;

  public static final String JSON_PROPERTY_BOT_INFO = "bot_info";
  @jakarta.annotation.Nullable private BotInfo botInfo;

  public static final String JSON_PROPERTY_IP_INFO = "ip_info";
  @jakarta.annotation.Nullable private IPInfo ipInfo;

  public static final String JSON_PROPERTY_PROXY = "proxy";
  @jakarta.annotation.Nullable private Boolean proxy;

  public static final String JSON_PROPERTY_PROXY_CONFIDENCE = "proxy_confidence";
  @jakarta.annotation.Nullable private ProxyConfidence proxyConfidence;

  public static final String JSON_PROPERTY_PROXY_DETAILS = "proxy_details";
  @jakarta.annotation.Nullable private ProxyDetails proxyDetails;

  public static final String JSON_PROPERTY_VPN = "vpn";
  @jakarta.annotation.Nullable private Boolean vpn;

  public static final String JSON_PROPERTY_VPN_CONFIDENCE = "vpn_confidence";
  @jakarta.annotation.Nullable private VpnConfidence vpnConfidence;

  public static final String JSON_PROPERTY_VPN_METHODS = "vpn_methods";
  @jakarta.annotation.Nullable private VpnMethods vpnMethods;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nonnull private EventSource source;

  public static final String JSON_PROPERTY_INCREMENTAL_IDENTIFICATION_STATUS =
      "incremental_identification_status";

  @jakarta.annotation.Nullable
  private IncrementalIdentificationStatus incrementalIdentificationStatus;

  public static final String JSON_PROPERTY_ENVIRONMENT_ID = "environment_id";
  @jakarta.annotation.Nullable private String environmentId;

  public static final String JSON_PROPERTY_SUSPECT = "suspect";
  @jakarta.annotation.Nullable private Boolean suspect;

  public static final String JSON_PROPERTY_SDK = "sdk";
  @jakarta.annotation.Nullable private SDK sdk;

  public static final String JSON_PROPERTY_REPLAYED = "replayed";
  @jakarta.annotation.Nullable private Boolean replayed;

  public static final String JSON_PROPERTY_IDENTIFICATION = "identification";
  @jakarta.annotation.Nullable private Identification identification;

  public static final String JSON_PROPERTY_SUPPLEMENTARY_ID_HIGH_RECALL =
      "supplementary_id_high_recall";
  @jakarta.annotation.Nullable private SupplementaryIDHighRecall supplementaryIdHighRecall;

  public static final String JSON_PROPERTY_BUNDLE_ID = "bundle_id";
  @jakarta.annotation.Nullable private String bundleId;

  public static final String JSON_PROPERTY_PACKAGE_NAME = "package_name";
  @jakarta.annotation.Nullable private String packageName;

  public static final String JSON_PROPERTY_IP_ADDRESS = "ip_address";
  @jakarta.annotation.Nullable private String ipAddress;

  public static final String JSON_PROPERTY_USER_AGENT = "user_agent";
  @jakarta.annotation.Nullable private String userAgent;

  public static final String JSON_PROPERTY_DEVICE = "device";
  @jakarta.annotation.Nullable private String device;

  public static final String JSON_PROPERTY_OS = "os";
  @jakarta.annotation.Nullable private String os;

  public static final String JSON_PROPERTY_OS_VERSION = "os_version";
  @jakarta.annotation.Nullable private String osVersion;

  public static final String JSON_PROPERTY_CLIENT_REFERRER = "client_referrer";
  @jakarta.annotation.Nullable private String clientReferrer;

  public static final String JSON_PROPERTY_BROWSER_DETAILS = "browser_details";
  @jakarta.annotation.Nullable private BrowserDetails browserDetails;

  public static final String JSON_PROPERTY_PROXIMITY = "proximity";
  @jakarta.annotation.Nullable private Proximity proximity;

  public static final String JSON_PROPERTY_ACTIVE_CALL = "active_call";
  @jakarta.annotation.Nullable private Boolean activeCall;

  public static final String JSON_PROPERTY_BOT = "bot";
  @jakarta.annotation.Nullable private BotResult bot;

  public static final String JSON_PROPERTY_BOT_TYPE = "bot_type";
  @jakarta.annotation.Nullable private String botType;

  public static final String JSON_PROPERTY_CLONED_APP = "cloned_app";
  @jakarta.annotation.Nullable private Boolean clonedApp;

  public static final String JSON_PROPERTY_DEVELOPER_TOOLS = "developer_tools";
  @jakarta.annotation.Nullable private Boolean developerTools;

  public static final String JSON_PROPERTY_EMULATOR = "emulator";
  @jakarta.annotation.Nullable private Boolean emulator;

  public static final String JSON_PROPERTY_FACTORY_RESET_TIMESTAMP = "factory_reset_timestamp";
  @jakarta.annotation.Nullable private Long factoryResetTimestamp;

  public static final String JSON_PROPERTY_FRIDA = "frida";
  @jakarta.annotation.Nullable private Boolean frida;

  public static final String JSON_PROPERTY_IP_BLOCKLIST = "ip_blocklist";
  @jakarta.annotation.Nullable private IPBlockList ipBlocklist;

  public static final String JSON_PROPERTY_PROXY_ML_SCORE = "proxy_ml_score";
  @jakarta.annotation.Nullable private Double proxyMlScore;

  public static final String JSON_PROPERTY_INCOGNITO = "incognito";
  @jakarta.annotation.Nullable private Boolean incognito;

  public static final String JSON_PROPERTY_JAILBROKEN = "jailbroken";
  @jakarta.annotation.Nullable private Boolean jailbroken;

  public static final String JSON_PROPERTY_LOCATION_SPOOFING = "location_spoofing";
  @jakarta.annotation.Nullable private Boolean locationSpoofing;

  public static final String JSON_PROPERTY_MITM_ATTACK = "mitm_attack";
  @jakarta.annotation.Nullable private Boolean mitmAttack;

  public static final String JSON_PROPERTY_PRIVACY_SETTINGS = "privacy_settings";
  @jakarta.annotation.Nullable private Boolean privacySettings;

  public static final String JSON_PROPERTY_ROOT_APPS = "root_apps";
  @jakarta.annotation.Nullable private Boolean rootApps;

  public static final String JSON_PROPERTY_RULE_ACTION = "rule_action";
  @jakarta.annotation.Nullable private EventRuleAction ruleAction;

  public static final String JSON_PROPERTY_SIMULATOR = "simulator";
  @jakarta.annotation.Nullable private Boolean simulator;

  public static final String JSON_PROPERTY_SUSPECT_SCORE = "suspect_score";
  @jakarta.annotation.Nullable private Integer suspectScore;

  public static final String JSON_PROPERTY_TAMPERING = "tampering";
  @jakarta.annotation.Nullable private Boolean tampering;

  public static final String JSON_PROPERTY_TAMPERING_CONFIDENCE = "tampering_confidence";
  @jakarta.annotation.Nullable private TamperingConfidence tamperingConfidence;

  public static final String JSON_PROPERTY_TAMPERING_ML_SCORE = "tampering_ml_score";
  @jakarta.annotation.Nullable private Double tamperingMlScore;

  public static final String JSON_PROPERTY_TAMPERING_DETAILS = "tampering_details";
  @jakarta.annotation.Nullable private TamperingDetails tamperingDetails;

  public static final String JSON_PROPERTY_VELOCITY = "velocity";
  @jakarta.annotation.Nullable private Velocity velocity;

  public static final String JSON_PROPERTY_VIRTUAL_MACHINE = "virtual_machine";
  @jakarta.annotation.Nullable private Boolean virtualMachine;

  public static final String JSON_PROPERTY_VIRTUAL_MACHINE_ML_SCORE = "virtual_machine_ml_score";
  @jakarta.annotation.Nullable private Double virtualMachineMlScore;

  public static final String JSON_PROPERTY_VPN_ML_SCORE = "vpn_ml_score";
  @jakarta.annotation.Nullable private Double vpnMlScore;

  public static final String JSON_PROPERTY_VPN_ORIGIN_TIMEZONE = "vpn_origin_timezone";
  @jakarta.annotation.Nullable private String vpnOriginTimezone;

  public static final String JSON_PROPERTY_VPN_ORIGIN_COUNTRY = "vpn_origin_country";
  @jakarta.annotation.Nullable private String vpnOriginCountry;

  public static final String JSON_PROPERTY_HIGH_ACTIVITY_DEVICE = "high_activity_device";
  @jakarta.annotation.Nullable private Boolean highActivityDevice;

  public static final String JSON_PROPERTY_RARE_DEVICE = "rare_device";
  @jakarta.annotation.Nullable private Boolean rareDevice;

  public static final String JSON_PROPERTY_RARE_DEVICE_PERCENTILE_BUCKET =
      "rare_device_percentile_bucket";
  @jakarta.annotation.Nullable private RareDevicePercentileBucket rareDevicePercentileBucket;

  public static final String JSON_PROPERTY_RAW_DEVICE_ATTRIBUTES = "raw_device_attributes";
  @jakarta.annotation.Nullable private RawDeviceAttributes rawDeviceAttributes;

  public static final String JSON_PROPERTY_LABELS = "labels";
  @jakarta.annotation.Nullable private List<LabelsInner> labels = new ArrayList<>();

  public EventDevice() {}

  public EventDevice eventId(@jakarta.annotation.Nonnull String eventId) {
    this.eventId = eventId;
    return this;
  }

  /**
   * Unique identifier of the user's request. The first portion of the event_id is a unix epoch milliseconds timestamp.
   * @return eventId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEventId() {
    return eventId;
  }

  @JsonProperty(value = JSON_PROPERTY_EVENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventId(@jakarta.annotation.Nonnull String eventId) {
    this.eventId = eventId;
  }

  public EventDevice timestamp(@jakarta.annotation.Nonnull Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Timestamp of the event with millisecond precision in Unix time.
   * @return timestamp
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getTimestamp() {
    return timestamp;
  }

  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@jakarta.annotation.Nonnull Long timestamp) {
    this.timestamp = timestamp;
  }

  public EventDevice linkedId(@jakarta.annotation.Nullable String linkedId) {
    this.linkedId = linkedId;
    return this;
  }

  /**
   * A customer-provided id that was sent with the request.
   * @return linkedId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLinkedId() {
    return linkedId;
  }

  @JsonProperty(value = JSON_PROPERTY_LINKED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkedId(@jakarta.annotation.Nullable String linkedId) {
    this.linkedId = linkedId;
  }

  public EventDevice tags(@jakarta.annotation.Nullable Map<String, Object> tags) {
    this.tags = tags;
    return this;
  }

  public EventDevice putTagsItem(String key, Object tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

  /**
   * A customer-provided value or an object that was sent with the identification request or updated later.
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getTags() {
    return tags;
  }

  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@jakarta.annotation.Nullable Map<String, Object> tags) {
    this.tags = tags;
  }

  public EventDevice url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Page URL from which the request was sent.
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }

  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }

  public EventDevice botInfo(@jakarta.annotation.Nullable BotInfo botInfo) {
    this.botInfo = botInfo;
    return this;
  }

  /**
   * Get botInfo
   * @return botInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BotInfo getBotInfo() {
    return botInfo;
  }

  @JsonProperty(value = JSON_PROPERTY_BOT_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBotInfo(@jakarta.annotation.Nullable BotInfo botInfo) {
    this.botInfo = botInfo;
  }

  public EventDevice ipInfo(@jakarta.annotation.Nullable IPInfo ipInfo) {
    this.ipInfo = ipInfo;
    return this;
  }

  /**
   * Get ipInfo
   * @return ipInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IPInfo getIpInfo() {
    return ipInfo;
  }

  @JsonProperty(value = JSON_PROPERTY_IP_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpInfo(@jakarta.annotation.Nullable IPInfo ipInfo) {
    this.ipInfo = ipInfo;
  }

  public EventDevice proxy(@jakarta.annotation.Nullable Boolean proxy) {
    this.proxy = proxy;
    return this;
  }

  /**
   * IP address was used by a public proxy provider or belonged to a known recent residential proxy
   * @return proxy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getProxy() {
    return proxy;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxy(@jakarta.annotation.Nullable Boolean proxy) {
    this.proxy = proxy;
  }

  public EventDevice proxyConfidence(@jakarta.annotation.Nullable ProxyConfidence proxyConfidence) {
    this.proxyConfidence = proxyConfidence;
    return this;
  }

  /**
   * Get proxyConfidence
   * @return proxyConfidence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyConfidence getProxyConfidence() {
    return proxyConfidence;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxyConfidence(@jakarta.annotation.Nullable ProxyConfidence proxyConfidence) {
    this.proxyConfidence = proxyConfidence;
  }

  public EventDevice proxyDetails(@jakarta.annotation.Nullable ProxyDetails proxyDetails) {
    this.proxyDetails = proxyDetails;
    return this;
  }

  /**
   * Get proxyDetails
   * @return proxyDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProxyDetails getProxyDetails() {
    return proxyDetails;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxyDetails(@jakarta.annotation.Nullable ProxyDetails proxyDetails) {
    this.proxyDetails = proxyDetails;
  }

  public EventDevice vpn(@jakarta.annotation.Nullable Boolean vpn) {
    this.vpn = vpn;
    return this;
  }

  /**
   * VPN or other anonymizing service has been used when sending the request.
   * @return vpn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getVpn() {
    return vpn;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpn(@jakarta.annotation.Nullable Boolean vpn) {
    this.vpn = vpn;
  }

  public EventDevice vpnConfidence(@jakarta.annotation.Nullable VpnConfidence vpnConfidence) {
    this.vpnConfidence = vpnConfidence;
    return this;
  }

  /**
   * Get vpnConfidence
   * @return vpnConfidence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VpnConfidence getVpnConfidence() {
    return vpnConfidence;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnConfidence(@jakarta.annotation.Nullable VpnConfidence vpnConfidence) {
    this.vpnConfidence = vpnConfidence;
  }

  public EventDevice vpnMethods(@jakarta.annotation.Nullable VpnMethods vpnMethods) {
    this.vpnMethods = vpnMethods;
    return this;
  }

  /**
   * Get vpnMethods
   * @return vpnMethods
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_METHODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VpnMethods getVpnMethods() {
    return vpnMethods;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_METHODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnMethods(@jakarta.annotation.Nullable VpnMethods vpnMethods) {
    this.vpnMethods = vpnMethods;
  }

  public EventDevice source(@jakarta.annotation.Nonnull EventSource source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EventSource getSource() {
    return source;
  }

  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSource(@jakarta.annotation.Nonnull EventSource source) {
    this.source = source;
  }

  public EventDevice incrementalIdentificationStatus(
      @jakarta.annotation.Nullable
          IncrementalIdentificationStatus incrementalIdentificationStatus) {
    this.incrementalIdentificationStatus = incrementalIdentificationStatus;
    return this;
  }

  /**
   * Get incrementalIdentificationStatus
   * @return incrementalIdentificationStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCREMENTAL_IDENTIFICATION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IncrementalIdentificationStatus getIncrementalIdentificationStatus() {
    return incrementalIdentificationStatus;
  }

  @JsonProperty(value = JSON_PROPERTY_INCREMENTAL_IDENTIFICATION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncrementalIdentificationStatus(
      @jakarta.annotation.Nullable
          IncrementalIdentificationStatus incrementalIdentificationStatus) {
    this.incrementalIdentificationStatus = incrementalIdentificationStatus;
  }

  public EventDevice environmentId(@jakarta.annotation.Nullable String environmentId) {
    this.environmentId = environmentId;
    return this;
  }

  /**
   * Environment Id of the event.
   * @return environmentId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEnvironmentId() {
    return environmentId;
  }

  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvironmentId(@jakarta.annotation.Nullable String environmentId) {
    this.environmentId = environmentId;
  }

  public EventDevice suspect(@jakarta.annotation.Nullable Boolean suspect) {
    this.suspect = suspect;
    return this;
  }

  /**
   * Field is `true` if you have previously set the `suspect` flag for this event using the [Server API Update event endpoint](https://docs.fingerprint.com/reference/server-api-update-event).
   * @return suspect
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUSPECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSuspect() {
    return suspect;
  }

  @JsonProperty(value = JSON_PROPERTY_SUSPECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuspect(@jakarta.annotation.Nullable Boolean suspect) {
    this.suspect = suspect;
  }

  public EventDevice sdk(@jakarta.annotation.Nullable SDK sdk) {
    this.sdk = sdk;
    return this;
  }

  /**
   * Get sdk
   * @return sdk
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SDK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SDK getSdk() {
    return sdk;
  }

  @JsonProperty(value = JSON_PROPERTY_SDK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSdk(@jakarta.annotation.Nullable SDK sdk) {
    this.sdk = sdk;
  }

  public EventDevice replayed(@jakarta.annotation.Nullable Boolean replayed) {
    this.replayed = replayed;
    return this;
  }

  /**
   * `true` if we determined that this payload was replayed, `false` otherwise.
   * @return replayed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLAYED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getReplayed() {
    return replayed;
  }

  @JsonProperty(value = JSON_PROPERTY_REPLAYED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplayed(@jakarta.annotation.Nullable Boolean replayed) {
    this.replayed = replayed;
  }

  public EventDevice identification(@jakarta.annotation.Nullable Identification identification) {
    this.identification = identification;
    return this;
  }

  /**
   * Get identification
   * @return identification
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDENTIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Identification getIdentification() {
    return identification;
  }

  @JsonProperty(value = JSON_PROPERTY_IDENTIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentification(@jakarta.annotation.Nullable Identification identification) {
    this.identification = identification;
  }

  public EventDevice supplementaryIdHighRecall(
      @jakarta.annotation.Nullable SupplementaryIDHighRecall supplementaryIdHighRecall) {
    this.supplementaryIdHighRecall = supplementaryIdHighRecall;
    return this;
  }

  /**
   * Get supplementaryIdHighRecall
   * @return supplementaryIdHighRecall
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUPPLEMENTARY_ID_HIGH_RECALL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SupplementaryIDHighRecall getSupplementaryIdHighRecall() {
    return supplementaryIdHighRecall;
  }

  @JsonProperty(value = JSON_PROPERTY_SUPPLEMENTARY_ID_HIGH_RECALL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplementaryIdHighRecall(
      @jakarta.annotation.Nullable SupplementaryIDHighRecall supplementaryIdHighRecall) {
    this.supplementaryIdHighRecall = supplementaryIdHighRecall;
  }

  public EventDevice bundleId(@jakarta.annotation.Nullable String bundleId) {
    this.bundleId = bundleId;
    return this;
  }

  /**
   * Bundle Id of the iOS application integrated with the Fingerprint SDK for the event.
   * @return bundleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUNDLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBundleId() {
    return bundleId;
  }

  @JsonProperty(value = JSON_PROPERTY_BUNDLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBundleId(@jakarta.annotation.Nullable String bundleId) {
    this.bundleId = bundleId;
  }

  public EventDevice packageName(@jakarta.annotation.Nullable String packageName) {
    this.packageName = packageName;
    return this;
  }

  /**
   * Package name of the Android application integrated with the Fingerprint SDK for the event.
   * @return packageName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PACKAGE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPackageName() {
    return packageName;
  }

  @JsonProperty(value = JSON_PROPERTY_PACKAGE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackageName(@jakarta.annotation.Nullable String packageName) {
    this.packageName = packageName;
  }

  public EventDevice ipAddress(@jakarta.annotation.Nullable String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * IP address of the requesting browser or bot.
   * @return ipAddress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IP_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIpAddress() {
    return ipAddress;
  }

  @JsonProperty(value = JSON_PROPERTY_IP_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpAddress(@jakarta.annotation.Nullable String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public EventDevice userAgent(@jakarta.annotation.Nullable String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  /**
   * User Agent of the client.
   * @return userAgent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUserAgent() {
    return userAgent;
  }

  @JsonProperty(value = JSON_PROPERTY_USER_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAgent(@jakarta.annotation.Nullable String userAgent) {
    this.userAgent = userAgent;
  }

  public EventDevice device(@jakarta.annotation.Nullable String device) {
    this.device = device;
    return this;
  }

  /**
   * Device model or family extracted from the user agent string. On web, this field is also present inside `browser_details`.
   * @return device
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDevice() {
    return device;
  }

  @JsonProperty(value = JSON_PROPERTY_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(@jakarta.annotation.Nullable String device) {
    this.device = device;
  }

  public EventDevice os(@jakarta.annotation.Nullable String os) {
    this.os = os;
    return this;
  }

  /**
   * Operating system family extracted from the user agent string. On web, this field is also present inside `browser_details`.
   * @return os
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOs() {
    return os;
  }

  @JsonProperty(value = JSON_PROPERTY_OS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOs(@jakarta.annotation.Nullable String os) {
    this.os = os;
  }

  public EventDevice osVersion(@jakarta.annotation.Nullable String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Operating system version string extracted from the user agent string. On web, this field is also present inside `browser_details`.
   * @return osVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OS_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOsVersion() {
    return osVersion;
  }

  @JsonProperty(value = JSON_PROPERTY_OS_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsVersion(@jakarta.annotation.Nullable String osVersion) {
    this.osVersion = osVersion;
  }

  public EventDevice clientReferrer(@jakarta.annotation.Nullable String clientReferrer) {
    this.clientReferrer = clientReferrer;
    return this;
  }

  /**
   * Client Referrer field corresponds to the `document.referrer` field gathered during an identification request. The value is an empty string if the user navigated to the page directly (not through a link, but, for example, by using a bookmark).
   * @return clientReferrer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERRER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getClientReferrer() {
    return clientReferrer;
  }

  @JsonProperty(value = JSON_PROPERTY_CLIENT_REFERRER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientReferrer(@jakarta.annotation.Nullable String clientReferrer) {
    this.clientReferrer = clientReferrer;
  }

  public EventDevice browserDetails(@jakarta.annotation.Nullable BrowserDetails browserDetails) {
    this.browserDetails = browserDetails;
    return this;
  }

  /**
   * Get browserDetails
   * @return browserDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BROWSER_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BrowserDetails getBrowserDetails() {
    return browserDetails;
  }

  @JsonProperty(value = JSON_PROPERTY_BROWSER_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrowserDetails(@jakarta.annotation.Nullable BrowserDetails browserDetails) {
    this.browserDetails = browserDetails;
  }

  public EventDevice proximity(@jakarta.annotation.Nullable Proximity proximity) {
    this.proximity = proximity;
    return this;
  }

  /**
   * Get proximity
   * @return proximity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXIMITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Proximity getProximity() {
    return proximity;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXIMITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProximity(@jakarta.annotation.Nullable Proximity proximity) {
    this.proximity = proximity;
  }

  public EventDevice activeCall(@jakarta.annotation.Nullable Boolean activeCall) {
    this.activeCall = activeCall;
    return this;
  }

  /**
   * Indicates whether the mobile device had an active call (cellular or VoIP) at the time of the request. Available from SDK 2.16.0+ on iOS and Android.
   * @return activeCall
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIVE_CALL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getActiveCall() {
    return activeCall;
  }

  @JsonProperty(value = JSON_PROPERTY_ACTIVE_CALL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActiveCall(@jakarta.annotation.Nullable Boolean activeCall) {
    this.activeCall = activeCall;
  }

  public EventDevice bot(@jakarta.annotation.Nullable BotResult bot) {
    this.bot = bot;
    return this;
  }

  /**
   * Get bot
   * @return bot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BotResult getBot() {
    return bot;
  }

  @JsonProperty(value = JSON_PROPERTY_BOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBot(@jakarta.annotation.Nullable BotResult bot) {
    this.bot = bot;
  }

  public EventDevice botType(@jakarta.annotation.Nullable String botType) {
    this.botType = botType;
    return this;
  }

  /**
   * Additional classification of the bot type if detected.
   * @return botType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBotType() {
    return botType;
  }

  @JsonProperty(value = JSON_PROPERTY_BOT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBotType(@jakarta.annotation.Nullable String botType) {
    this.botType = botType;
  }

  public EventDevice clonedApp(@jakarta.annotation.Nullable Boolean clonedApp) {
    this.clonedApp = clonedApp;
    return this;
  }

  /**
   * Android specific cloned application detection. There are 2 values:  * `true` - Presence of app cloners work detected (e.g. fully cloned application found or launch of it inside of a not main working profile detected). * `false` - No signs of cloned application detected or the client is not Android.
   * @return clonedApp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLONED_APP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getClonedApp() {
    return clonedApp;
  }

  @JsonProperty(value = JSON_PROPERTY_CLONED_APP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClonedApp(@jakarta.annotation.Nullable Boolean clonedApp) {
    this.clonedApp = clonedApp;
  }

  public EventDevice developerTools(@jakarta.annotation.Nullable Boolean developerTools) {
    this.developerTools = developerTools;
    return this;
  }

  /**
   * `true` if the browser has DevTools open (Chrome, Firefox) or the Android/iOS device has Developer Tools enabled, `false` otherwise.
   * @return developerTools
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDeveloperTools() {
    return developerTools;
  }

  @JsonProperty(value = JSON_PROPERTY_DEVELOPER_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeveloperTools(@jakarta.annotation.Nullable Boolean developerTools) {
    this.developerTools = developerTools;
  }

  public EventDevice emulator(@jakarta.annotation.Nullable Boolean emulator) {
    this.emulator = emulator;
    return this;
  }

  /**
   * Android specific emulator detection. There are 2 values:  * `true` - Emulated environment detected (e.g. launch inside of AVD).  * `false` - No signs of emulated environment detected or the client is not Android.
   * @return emulator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMULATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEmulator() {
    return emulator;
  }

  @JsonProperty(value = JSON_PROPERTY_EMULATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmulator(@jakarta.annotation.Nullable Boolean emulator) {
    this.emulator = emulator;
  }

  public EventDevice factoryResetTimestamp(
      @jakarta.annotation.Nullable Long factoryResetTimestamp) {
    this.factoryResetTimestamp = factoryResetTimestamp;
    return this;
  }

  /**
   * The time of the most recent factory reset that happened on the **mobile device** is expressed as Unix epoch time. When a factory reset cannot be detected on the mobile device or when the request is initiated from a browser,  this field will correspond to the *epoch* time (i.e 1 Jan 1970 UTC) as a value of 0. See [Factory Reset Detection](https://docs.fingerprint.com/docs/smart-signals-reference#factory-reset-detection) to learn more about this Smart Signal.
   * @return factoryResetTimestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FACTORY_RESET_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getFactoryResetTimestamp() {
    return factoryResetTimestamp;
  }

  @JsonProperty(value = JSON_PROPERTY_FACTORY_RESET_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFactoryResetTimestamp(@jakarta.annotation.Nullable Long factoryResetTimestamp) {
    this.factoryResetTimestamp = factoryResetTimestamp;
  }

  public EventDevice frida(@jakarta.annotation.Nullable Boolean frida) {
    this.frida = frida;
    return this;
  }

  /**
   * [Frida](https://frida.re/docs/) detection for Android and iOS devices. There are 2 values: * `true` - Frida detected * `false` - No signs of Frida or the client is not a mobile device.
   * @return frida
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FRIDA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getFrida() {
    return frida;
  }

  @JsonProperty(value = JSON_PROPERTY_FRIDA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrida(@jakarta.annotation.Nullable Boolean frida) {
    this.frida = frida;
  }

  public EventDevice ipBlocklist(@jakarta.annotation.Nullable IPBlockList ipBlocklist) {
    this.ipBlocklist = ipBlocklist;
    return this;
  }

  /**
   * Get ipBlocklist
   * @return ipBlocklist
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IP_BLOCKLIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IPBlockList getIpBlocklist() {
    return ipBlocklist;
  }

  @JsonProperty(value = JSON_PROPERTY_IP_BLOCKLIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpBlocklist(@jakarta.annotation.Nullable IPBlockList ipBlocklist) {
    this.ipBlocklist = ipBlocklist;
  }

  public EventDevice proxyMlScore(@jakarta.annotation.Nullable Double proxyMlScore) {
    this.proxyMlScore = proxyMlScore;
    return this;
  }

  /**
   * Machine learning–based proxy score, represented as a floating-point value between 0 and 1 (inclusive), with up to three decimal places of precision. A higher score means a higher confidence in the positive `proxy` detection result. This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/).
   * minimum: 0
   * maximum: 1
   * @return proxyMlScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROXY_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getProxyMlScore() {
    return proxyMlScore;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxyMlScore(@jakarta.annotation.Nullable Double proxyMlScore) {
    this.proxyMlScore = proxyMlScore;
  }

  public EventDevice incognito(@jakarta.annotation.Nullable Boolean incognito) {
    this.incognito = incognito;
    return this;
  }

  /**
   * `true` if we detected incognito mode used in the browser, `false` otherwise.
   * @return incognito
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCOGNITO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncognito() {
    return incognito;
  }

  @JsonProperty(value = JSON_PROPERTY_INCOGNITO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncognito(@jakarta.annotation.Nullable Boolean incognito) {
    this.incognito = incognito;
  }

  public EventDevice jailbroken(@jakarta.annotation.Nullable Boolean jailbroken) {
    this.jailbroken = jailbroken;
    return this;
  }

  /**
   * iOS specific jailbreak detection. There are 2 values:  * `true` - Jailbreak detected. * `false` - No signs of jailbreak or the client is not iOS.
   * @return jailbroken
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_JAILBROKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getJailbroken() {
    return jailbroken;
  }

  @JsonProperty(value = JSON_PROPERTY_JAILBROKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJailbroken(@jakarta.annotation.Nullable Boolean jailbroken) {
    this.jailbroken = jailbroken;
  }

  public EventDevice locationSpoofing(@jakarta.annotation.Nullable Boolean locationSpoofing) {
    this.locationSpoofing = locationSpoofing;
    return this;
  }

  /**
   * Flag indicating whether the request came from a mobile device with location spoofing enabled.
   * @return locationSpoofing
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION_SPOOFING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getLocationSpoofing() {
    return locationSpoofing;
  }

  @JsonProperty(value = JSON_PROPERTY_LOCATION_SPOOFING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationSpoofing(@jakarta.annotation.Nullable Boolean locationSpoofing) {
    this.locationSpoofing = locationSpoofing;
  }

  public EventDevice mitmAttack(@jakarta.annotation.Nullable Boolean mitmAttack) {
    this.mitmAttack = mitmAttack;
    return this;
  }

  /**
   * * `true` - When requests made from your users' mobile devices to Fingerprint servers have been intercepted and potentially modified.  * `false` - Otherwise or when the request originated from a browser. See [MitM Attack Detection](https://docs.fingerprint.com/docs/smart-signals-reference#mitm-attack-detection) to learn more about this Smart Signal.
   * @return mitmAttack
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MITM_ATTACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMitmAttack() {
    return mitmAttack;
  }

  @JsonProperty(value = JSON_PROPERTY_MITM_ATTACK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMitmAttack(@jakarta.annotation.Nullable Boolean mitmAttack) {
    this.mitmAttack = mitmAttack;
  }

  public EventDevice privacySettings(@jakarta.annotation.Nullable Boolean privacySettings) {
    this.privacySettings = privacySettings;
    return this;
  }

  /**
   * `true` if the request is from a privacy aware browser (e.g. Tor) or from a browser in which fingerprinting is blocked. Otherwise `false`.
   * @return privacySettings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIVACY_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getPrivacySettings() {
    return privacySettings;
  }

  @JsonProperty(value = JSON_PROPERTY_PRIVACY_SETTINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivacySettings(@jakarta.annotation.Nullable Boolean privacySettings) {
    this.privacySettings = privacySettings;
  }

  public EventDevice rootApps(@jakarta.annotation.Nullable Boolean rootApps) {
    this.rootApps = rootApps;
    return this;
  }

  /**
   * Android specific root management apps detection. There are 2 values:  * `true` - Root Management Apps detected (e.g. Magisk). * `false` - No Root Management Apps detected or the client isn't Android.
   * @return rootApps
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROOT_APPS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRootApps() {
    return rootApps;
  }

  @JsonProperty(value = JSON_PROPERTY_ROOT_APPS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRootApps(@jakarta.annotation.Nullable Boolean rootApps) {
    this.rootApps = rootApps;
  }

  public EventDevice ruleAction(@jakarta.annotation.Nullable EventRuleAction ruleAction) {
    this.ruleAction = ruleAction;
    return this;
  }

  /**
   * Get ruleAction
   * @return ruleAction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULE_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EventRuleAction getRuleAction() {
    return ruleAction;
  }

  @JsonProperty(value = JSON_PROPERTY_RULE_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuleAction(@jakarta.annotation.Nullable EventRuleAction ruleAction) {
    this.ruleAction = ruleAction;
  }

  public EventDevice simulator(@jakarta.annotation.Nullable Boolean simulator) {
    this.simulator = simulator;
    return this;
  }

  /**
   * iOS specific simulator detection. There are 2 values: * `true` - Simulator environment detected. * `false` - No signs of simulator or the client is not iOS.
   * @return simulator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIMULATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSimulator() {
    return simulator;
  }

  @JsonProperty(value = JSON_PROPERTY_SIMULATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSimulator(@jakarta.annotation.Nullable Boolean simulator) {
    this.simulator = simulator;
  }

  public EventDevice suspectScore(@jakarta.annotation.Nullable Integer suspectScore) {
    this.suspectScore = suspectScore;
    return this;
  }

  /**
   * Suspect Score is an easy way to integrate Smart Signals into your fraud protection work flow.  It is a weighted representation of all Smart Signals present in the payload that helps identify suspicious activity. The value range is [0; S] where S is sum of all Smart Signals weights.  See more details here: https://docs.fingerprint.com/docs/suspect-score
   * @return suspectScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUSPECT_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getSuspectScore() {
    return suspectScore;
  }

  @JsonProperty(value = JSON_PROPERTY_SUSPECT_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuspectScore(@jakarta.annotation.Nullable Integer suspectScore) {
    this.suspectScore = suspectScore;
  }

  public EventDevice tampering(@jakarta.annotation.Nullable Boolean tampering) {
    this.tampering = tampering;
    return this;
  }

  /**
   * The field can be used as a standalone flag for tampering detection. Alternatively, the more granular fields documented below can be used for workflows that require more context. * `true` if tampering is detected through an anomalous browser signature, anti-detect browser detection, or other tampering-related methods * `false` if none of the tampering checks return a positive result
   * @return tampering
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAMPERING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getTampering() {
    return tampering;
  }

  @JsonProperty(value = JSON_PROPERTY_TAMPERING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTampering(@jakarta.annotation.Nullable Boolean tampering) {
    this.tampering = tampering;
  }

  public EventDevice tamperingConfidence(
      @jakarta.annotation.Nullable TamperingConfidence tamperingConfidence) {
    this.tamperingConfidence = tamperingConfidence;
    return this;
  }

  /**
   * Get tamperingConfidence
   * @return tamperingConfidence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAMPERING_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TamperingConfidence getTamperingConfidence() {
    return tamperingConfidence;
  }

  @JsonProperty(value = JSON_PROPERTY_TAMPERING_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTamperingConfidence(
      @jakarta.annotation.Nullable TamperingConfidence tamperingConfidence) {
    this.tamperingConfidence = tamperingConfidence;
  }

  public EventDevice tamperingMlScore(@jakarta.annotation.Nullable Double tamperingMlScore) {
    this.tamperingMlScore = tamperingMlScore;
    return this;
  }

  /**
   * The output of this model is captured as tampering_ml_score, a number indicating how likely an event is coming from an anti detect browser. Values close to 1 signify higher confidence and we consider anything above the threshold of 0.8 to be actionable (the result and anti_detect_browser fields conveniently captures that fact)
   * minimum: 0
   * maximum: 1
   * @return tamperingMlScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAMPERING_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getTamperingMlScore() {
    return tamperingMlScore;
  }

  @JsonProperty(value = JSON_PROPERTY_TAMPERING_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTamperingMlScore(@jakarta.annotation.Nullable Double tamperingMlScore) {
    this.tamperingMlScore = tamperingMlScore;
  }

  public EventDevice tamperingDetails(
      @jakarta.annotation.Nullable TamperingDetails tamperingDetails) {
    this.tamperingDetails = tamperingDetails;
    return this;
  }

  /**
   * Get tamperingDetails
   * @return tamperingDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAMPERING_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TamperingDetails getTamperingDetails() {
    return tamperingDetails;
  }

  @JsonProperty(value = JSON_PROPERTY_TAMPERING_DETAILS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTamperingDetails(@jakarta.annotation.Nullable TamperingDetails tamperingDetails) {
    this.tamperingDetails = tamperingDetails;
  }

  public EventDevice velocity(@jakarta.annotation.Nullable Velocity velocity) {
    this.velocity = velocity;
    return this;
  }

  /**
   * Get velocity
   * @return velocity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VELOCITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Velocity getVelocity() {
    return velocity;
  }

  @JsonProperty(value = JSON_PROPERTY_VELOCITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVelocity(@jakarta.annotation.Nullable Velocity velocity) {
    this.velocity = velocity;
  }

  public EventDevice virtualMachine(@jakarta.annotation.Nullable Boolean virtualMachine) {
    this.virtualMachine = virtualMachine;
    return this;
  }

  /**
   * `true` if the request came from a browser running inside a virtual machine (e.g. VMWare), `false` otherwise.
   * @return virtualMachine
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIRTUAL_MACHINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getVirtualMachine() {
    return virtualMachine;
  }

  @JsonProperty(value = JSON_PROPERTY_VIRTUAL_MACHINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVirtualMachine(@jakarta.annotation.Nullable Boolean virtualMachine) {
    this.virtualMachine = virtualMachine;
  }

  public EventDevice virtualMachineMlScore(
      @jakarta.annotation.Nullable Double virtualMachineMlScore) {
    this.virtualMachineMlScore = virtualMachineMlScore;
    return this;
  }

  /**
   * Machine learning–based virtual machine score, represented as a floating-point value between 0 and 1 (inclusive), with up to three decimal places of precision. A higher score means a higher confidence in the positive `virtual_machine` detection result. This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/).
   * minimum: 0
   * maximum: 1
   * @return virtualMachineMlScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIRTUAL_MACHINE_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getVirtualMachineMlScore() {
    return virtualMachineMlScore;
  }

  @JsonProperty(value = JSON_PROPERTY_VIRTUAL_MACHINE_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVirtualMachineMlScore(@jakarta.annotation.Nullable Double virtualMachineMlScore) {
    this.virtualMachineMlScore = virtualMachineMlScore;
  }

  public EventDevice vpnMlScore(@jakarta.annotation.Nullable Double vpnMlScore) {
    this.vpnMlScore = vpnMlScore;
    return this;
  }

  /**
   * Machine learning–based VPN score, represented as a floating-point value between 0 and 1 (inclusive), with up to three decimal places of precision. A higher score means a higher confidence in the positive `vpn` detection result. This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/).
   * minimum: 0
   * maximum: 1
   * @return vpnMlScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getVpnMlScore() {
    return vpnMlScore;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnMlScore(@jakarta.annotation.Nullable Double vpnMlScore) {
    this.vpnMlScore = vpnMlScore;
  }

  public EventDevice vpnOriginTimezone(@jakarta.annotation.Nullable String vpnOriginTimezone) {
    this.vpnOriginTimezone = vpnOriginTimezone;
    return this;
  }

  /**
   * Local timezone which is used in timezone_mismatch method.
   * @return vpnOriginTimezone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_ORIGIN_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVpnOriginTimezone() {
    return vpnOriginTimezone;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_ORIGIN_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnOriginTimezone(@jakarta.annotation.Nullable String vpnOriginTimezone) {
    this.vpnOriginTimezone = vpnOriginTimezone;
  }

  public EventDevice vpnOriginCountry(@jakarta.annotation.Nullable String vpnOriginCountry) {
    this.vpnOriginCountry = vpnOriginCountry;
    return this;
  }

  /**
   * Country of the request (Android SDK version >= 2.4.0, iOS SDK version >= 2.9.0, JS agent >= 3.12.9 / 4.0.2), ISO 3166 format or unknown.
   * @return vpnOriginCountry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VPN_ORIGIN_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVpnOriginCountry() {
    return vpnOriginCountry;
  }

  @JsonProperty(value = JSON_PROPERTY_VPN_ORIGIN_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVpnOriginCountry(@jakarta.annotation.Nullable String vpnOriginCountry) {
    this.vpnOriginCountry = vpnOriginCountry;
  }

  public EventDevice highActivityDevice(@jakarta.annotation.Nullable Boolean highActivityDevice) {
    this.highActivityDevice = highActivityDevice;
    return this;
  }

  /**
   * Flag indicating if the request came from a high-activity visitor.
   * @return highActivityDevice
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIGH_ACTIVITY_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHighActivityDevice() {
    return highActivityDevice;
  }

  @JsonProperty(value = JSON_PROPERTY_HIGH_ACTIVITY_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighActivityDevice(@jakarta.annotation.Nullable Boolean highActivityDevice) {
    this.highActivityDevice = highActivityDevice;
  }

  public EventDevice rareDevice(@jakarta.annotation.Nullable Boolean rareDevice) {
    this.rareDevice = rareDevice;
    return this;
  }

  /**
   * `true` if the device is considered rare based on its combination of hardware and software attributes.  A device is classified as rare if it falls within the top 99.9 percentile (lowest-frequency segment) of observed traffic,  or if its configuration has not been previously seen (`not_seen`). > This Smart Signal is currently in beta and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/).
   * @return rareDevice
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RARE_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRareDevice() {
    return rareDevice;
  }

  @JsonProperty(value = JSON_PROPERTY_RARE_DEVICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRareDevice(@jakarta.annotation.Nullable Boolean rareDevice) {
    this.rareDevice = rareDevice;
  }

  public EventDevice rareDevicePercentileBucket(
      @jakarta.annotation.Nullable RareDevicePercentileBucket rareDevicePercentileBucket) {
    this.rareDevicePercentileBucket = rareDevicePercentileBucket;
    return this;
  }

  /**
   * Get rareDevicePercentileBucket
   * @return rareDevicePercentileBucket
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RARE_DEVICE_PERCENTILE_BUCKET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RareDevicePercentileBucket getRareDevicePercentileBucket() {
    return rareDevicePercentileBucket;
  }

  @JsonProperty(value = JSON_PROPERTY_RARE_DEVICE_PERCENTILE_BUCKET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRareDevicePercentileBucket(
      @jakarta.annotation.Nullable RareDevicePercentileBucket rareDevicePercentileBucket) {
    this.rareDevicePercentileBucket = rareDevicePercentileBucket;
  }

  public EventDevice rawDeviceAttributes(
      @jakarta.annotation.Nullable RawDeviceAttributes rawDeviceAttributes) {
    this.rawDeviceAttributes = rawDeviceAttributes;
    return this;
  }

  /**
   * Get rawDeviceAttributes
   * @return rawDeviceAttributes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RAW_DEVICE_ATTRIBUTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RawDeviceAttributes getRawDeviceAttributes() {
    return rawDeviceAttributes;
  }

  @JsonProperty(value = JSON_PROPERTY_RAW_DEVICE_ATTRIBUTES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRawDeviceAttributes(
      @jakarta.annotation.Nullable RawDeviceAttributes rawDeviceAttributes) {
    this.rawDeviceAttributes = rawDeviceAttributes;
  }

  public EventDevice labels(@jakarta.annotation.Nullable List<LabelsInner> labels) {
    this.labels = labels;
    return this;
  }

  public EventDevice addLabelsItem(LabelsInner labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Each label returns a prediction (true or false) for a specific use case (label field) based on a machine learning score. The machine learning score is determined by a model trained on customer data for that use case. This field is in the beta phase and only available to select customers. If you are interested, please [contact our support team](https://fingerprint.com/support/).
   * @return labels
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LABELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LabelsInner> getLabels() {
    return labels;
  }

  @JsonProperty(value = JSON_PROPERTY_LABELS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabels(@jakarta.annotation.Nullable List<LabelsInner> labels) {
    this.labels = labels;
  }

  /**
   * Return true if this EventDevice object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventDevice eventDevice = (EventDevice) o;
    return Objects.equals(this.eventId, eventDevice.eventId)
        && Objects.equals(this.timestamp, eventDevice.timestamp)
        && Objects.equals(this.linkedId, eventDevice.linkedId)
        && Objects.equals(this.tags, eventDevice.tags)
        && Objects.equals(this.url, eventDevice.url)
        && Objects.equals(this.botInfo, eventDevice.botInfo)
        && Objects.equals(this.ipInfo, eventDevice.ipInfo)
        && Objects.equals(this.proxy, eventDevice.proxy)
        && Objects.equals(this.proxyConfidence, eventDevice.proxyConfidence)
        && Objects.equals(this.proxyDetails, eventDevice.proxyDetails)
        && Objects.equals(this.vpn, eventDevice.vpn)
        && Objects.equals(this.vpnConfidence, eventDevice.vpnConfidence)
        && Objects.equals(this.vpnMethods, eventDevice.vpnMethods)
        && Objects.equals(this.source, eventDevice.source)
        && Objects.equals(
            this.incrementalIdentificationStatus, eventDevice.incrementalIdentificationStatus)
        && Objects.equals(this.environmentId, eventDevice.environmentId)
        && Objects.equals(this.suspect, eventDevice.suspect)
        && Objects.equals(this.sdk, eventDevice.sdk)
        && Objects.equals(this.replayed, eventDevice.replayed)
        && Objects.equals(this.identification, eventDevice.identification)
        && Objects.equals(this.supplementaryIdHighRecall, eventDevice.supplementaryIdHighRecall)
        && Objects.equals(this.bundleId, eventDevice.bundleId)
        && Objects.equals(this.packageName, eventDevice.packageName)
        && Objects.equals(this.ipAddress, eventDevice.ipAddress)
        && Objects.equals(this.userAgent, eventDevice.userAgent)
        && Objects.equals(this.device, eventDevice.device)
        && Objects.equals(this.os, eventDevice.os)
        && Objects.equals(this.osVersion, eventDevice.osVersion)
        && Objects.equals(this.clientReferrer, eventDevice.clientReferrer)
        && Objects.equals(this.browserDetails, eventDevice.browserDetails)
        && Objects.equals(this.proximity, eventDevice.proximity)
        && Objects.equals(this.activeCall, eventDevice.activeCall)
        && Objects.equals(this.bot, eventDevice.bot)
        && Objects.equals(this.botType, eventDevice.botType)
        && Objects.equals(this.clonedApp, eventDevice.clonedApp)
        && Objects.equals(this.developerTools, eventDevice.developerTools)
        && Objects.equals(this.emulator, eventDevice.emulator)
        && Objects.equals(this.factoryResetTimestamp, eventDevice.factoryResetTimestamp)
        && Objects.equals(this.frida, eventDevice.frida)
        && Objects.equals(this.ipBlocklist, eventDevice.ipBlocklist)
        && Objects.equals(this.proxyMlScore, eventDevice.proxyMlScore)
        && Objects.equals(this.incognito, eventDevice.incognito)
        && Objects.equals(this.jailbroken, eventDevice.jailbroken)
        && Objects.equals(this.locationSpoofing, eventDevice.locationSpoofing)
        && Objects.equals(this.mitmAttack, eventDevice.mitmAttack)
        && Objects.equals(this.privacySettings, eventDevice.privacySettings)
        && Objects.equals(this.rootApps, eventDevice.rootApps)
        && Objects.equals(this.ruleAction, eventDevice.ruleAction)
        && Objects.equals(this.simulator, eventDevice.simulator)
        && Objects.equals(this.suspectScore, eventDevice.suspectScore)
        && Objects.equals(this.tampering, eventDevice.tampering)
        && Objects.equals(this.tamperingConfidence, eventDevice.tamperingConfidence)
        && Objects.equals(this.tamperingMlScore, eventDevice.tamperingMlScore)
        && Objects.equals(this.tamperingDetails, eventDevice.tamperingDetails)
        && Objects.equals(this.velocity, eventDevice.velocity)
        && Objects.equals(this.virtualMachine, eventDevice.virtualMachine)
        && Objects.equals(this.virtualMachineMlScore, eventDevice.virtualMachineMlScore)
        && Objects.equals(this.vpnMlScore, eventDevice.vpnMlScore)
        && Objects.equals(this.vpnOriginTimezone, eventDevice.vpnOriginTimezone)
        && Objects.equals(this.vpnOriginCountry, eventDevice.vpnOriginCountry)
        && Objects.equals(this.highActivityDevice, eventDevice.highActivityDevice)
        && Objects.equals(this.rareDevice, eventDevice.rareDevice)
        && Objects.equals(this.rareDevicePercentileBucket, eventDevice.rareDevicePercentileBucket)
        && Objects.equals(this.rawDeviceAttributes, eventDevice.rawDeviceAttributes)
        && Objects.equals(this.labels, eventDevice.labels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        eventId,
        timestamp,
        linkedId,
        tags,
        url,
        botInfo,
        ipInfo,
        proxy,
        proxyConfidence,
        proxyDetails,
        vpn,
        vpnConfidence,
        vpnMethods,
        source,
        incrementalIdentificationStatus,
        environmentId,
        suspect,
        sdk,
        replayed,
        identification,
        supplementaryIdHighRecall,
        bundleId,
        packageName,
        ipAddress,
        userAgent,
        device,
        os,
        osVersion,
        clientReferrer,
        browserDetails,
        proximity,
        activeCall,
        bot,
        botType,
        clonedApp,
        developerTools,
        emulator,
        factoryResetTimestamp,
        frida,
        ipBlocklist,
        proxyMlScore,
        incognito,
        jailbroken,
        locationSpoofing,
        mitmAttack,
        privacySettings,
        rootApps,
        ruleAction,
        simulator,
        suspectScore,
        tampering,
        tamperingConfidence,
        tamperingMlScore,
        tamperingDetails,
        velocity,
        virtualMachine,
        virtualMachineMlScore,
        vpnMlScore,
        vpnOriginTimezone,
        vpnOriginCountry,
        highActivityDevice,
        rareDevice,
        rareDevicePercentileBucket,
        rawDeviceAttributes,
        labels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventDevice {\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    linkedId: ").append(toIndentedString(linkedId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    botInfo: ").append(toIndentedString(botInfo)).append("\n");
    sb.append("    ipInfo: ").append(toIndentedString(ipInfo)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("    proxyConfidence: ").append(toIndentedString(proxyConfidence)).append("\n");
    sb.append("    proxyDetails: ").append(toIndentedString(proxyDetails)).append("\n");
    sb.append("    vpn: ").append(toIndentedString(vpn)).append("\n");
    sb.append("    vpnConfidence: ").append(toIndentedString(vpnConfidence)).append("\n");
    sb.append("    vpnMethods: ").append(toIndentedString(vpnMethods)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    incrementalIdentificationStatus: ")
        .append(toIndentedString(incrementalIdentificationStatus))
        .append("\n");
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    suspect: ").append(toIndentedString(suspect)).append("\n");
    sb.append("    sdk: ").append(toIndentedString(sdk)).append("\n");
    sb.append("    replayed: ").append(toIndentedString(replayed)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    supplementaryIdHighRecall: ")
        .append(toIndentedString(supplementaryIdHighRecall))
        .append("\n");
    sb.append("    bundleId: ").append(toIndentedString(bundleId)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    clientReferrer: ").append(toIndentedString(clientReferrer)).append("\n");
    sb.append("    browserDetails: ").append(toIndentedString(browserDetails)).append("\n");
    sb.append("    proximity: ").append(toIndentedString(proximity)).append("\n");
    sb.append("    activeCall: ").append(toIndentedString(activeCall)).append("\n");
    sb.append("    bot: ").append(toIndentedString(bot)).append("\n");
    sb.append("    botType: ").append(toIndentedString(botType)).append("\n");
    sb.append("    clonedApp: ").append(toIndentedString(clonedApp)).append("\n");
    sb.append("    developerTools: ").append(toIndentedString(developerTools)).append("\n");
    sb.append("    emulator: ").append(toIndentedString(emulator)).append("\n");
    sb.append("    factoryResetTimestamp: ")
        .append(toIndentedString(factoryResetTimestamp))
        .append("\n");
    sb.append("    frida: ").append(toIndentedString(frida)).append("\n");
    sb.append("    ipBlocklist: ").append(toIndentedString(ipBlocklist)).append("\n");
    sb.append("    proxyMlScore: ").append(toIndentedString(proxyMlScore)).append("\n");
    sb.append("    incognito: ").append(toIndentedString(incognito)).append("\n");
    sb.append("    jailbroken: ").append(toIndentedString(jailbroken)).append("\n");
    sb.append("    locationSpoofing: ").append(toIndentedString(locationSpoofing)).append("\n");
    sb.append("    mitmAttack: ").append(toIndentedString(mitmAttack)).append("\n");
    sb.append("    privacySettings: ").append(toIndentedString(privacySettings)).append("\n");
    sb.append("    rootApps: ").append(toIndentedString(rootApps)).append("\n");
    sb.append("    ruleAction: ").append(toIndentedString(ruleAction)).append("\n");
    sb.append("    simulator: ").append(toIndentedString(simulator)).append("\n");
    sb.append("    suspectScore: ").append(toIndentedString(suspectScore)).append("\n");
    sb.append("    tampering: ").append(toIndentedString(tampering)).append("\n");
    sb.append("    tamperingConfidence: ")
        .append(toIndentedString(tamperingConfidence))
        .append("\n");
    sb.append("    tamperingMlScore: ").append(toIndentedString(tamperingMlScore)).append("\n");
    sb.append("    tamperingDetails: ").append(toIndentedString(tamperingDetails)).append("\n");
    sb.append("    velocity: ").append(toIndentedString(velocity)).append("\n");
    sb.append("    virtualMachine: ").append(toIndentedString(virtualMachine)).append("\n");
    sb.append("    virtualMachineMlScore: ")
        .append(toIndentedString(virtualMachineMlScore))
        .append("\n");
    sb.append("    vpnMlScore: ").append(toIndentedString(vpnMlScore)).append("\n");
    sb.append("    vpnOriginTimezone: ").append(toIndentedString(vpnOriginTimezone)).append("\n");
    sb.append("    vpnOriginCountry: ").append(toIndentedString(vpnOriginCountry)).append("\n");
    sb.append("    highActivityDevice: ").append(toIndentedString(highActivityDevice)).append("\n");
    sb.append("    rareDevice: ").append(toIndentedString(rareDevice)).append("\n");
    sb.append("    rareDevicePercentileBucket: ")
        .append(toIndentedString(rareDevicePercentileBucket))
        .append("\n");
    sb.append("    rawDeviceAttributes: ")
        .append(toIndentedString(rawDeviceAttributes))
        .append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
