/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * Informs the client that the request should be forwarded to the origin with optional request header modifications.
 */
@JsonPropertyOrder({
  EventRuleActionAllow.JSON_PROPERTY_RULESET_ID,
  EventRuleActionAllow.JSON_PROPERTY_RULE_ID,
  EventRuleActionAllow.JSON_PROPERTY_RULE_EXPRESSION,
  EventRuleActionAllow.JSON_PROPERTY_TYPE,
  EventRuleActionAllow.JSON_PROPERTY_REQUEST_HEADER_MODIFICATIONS
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.16.0")
public class EventRuleActionAllow implements EventRuleAction {
  public static final String JSON_PROPERTY_RULESET_ID = "ruleset_id";
  @jakarta.annotation.Nonnull private String rulesetId;

  public static final String JSON_PROPERTY_RULE_ID = "rule_id";
  @jakarta.annotation.Nullable private String ruleId;

  public static final String JSON_PROPERTY_RULE_EXPRESSION = "rule_expression";
  @jakarta.annotation.Nullable private String ruleExpression;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull private RuleActionType type;

  public static final String JSON_PROPERTY_REQUEST_HEADER_MODIFICATIONS =
      "request_header_modifications";
  @jakarta.annotation.Nullable private RequestHeaderModifications requestHeaderModifications;

  public EventRuleActionAllow() {}

  public EventRuleActionAllow rulesetId(@jakarta.annotation.Nonnull String rulesetId) {
    this.rulesetId = rulesetId;
    return this;
  }

  /**
   * The ID of the evaluated ruleset.
   * @return rulesetId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getRulesetId() {
    return rulesetId;
  }

  @JsonProperty(value = JSON_PROPERTY_RULESET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRulesetId(@jakarta.annotation.Nonnull String rulesetId) {
    this.rulesetId = rulesetId;
  }

  public EventRuleActionAllow ruleId(@jakarta.annotation.Nullable String ruleId) {
    this.ruleId = ruleId;
    return this;
  }

  /**
   * The ID of the rule that matched the identification event.
   * @return ruleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRuleId() {
    return ruleId;
  }

  @JsonProperty(value = JSON_PROPERTY_RULE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuleId(@jakarta.annotation.Nullable String ruleId) {
    this.ruleId = ruleId;
  }

  public EventRuleActionAllow ruleExpression(@jakarta.annotation.Nullable String ruleExpression) {
    this.ruleExpression = ruleExpression;
    return this;
  }

  /**
   * The expression of the rule that matched the identification event.
   * @return ruleExpression
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULE_EXPRESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRuleExpression() {
    return ruleExpression;
  }

  @JsonProperty(value = JSON_PROPERTY_RULE_EXPRESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuleExpression(@jakarta.annotation.Nullable String ruleExpression) {
    this.ruleExpression = ruleExpression;
  }

  public EventRuleActionAllow type(@jakarta.annotation.Nonnull RuleActionType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RuleActionType getType() {
    return type;
  }

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull RuleActionType type) {
    this.type = type;
  }

  public EventRuleActionAllow requestHeaderModifications(
      @jakarta.annotation.Nullable RequestHeaderModifications requestHeaderModifications) {
    this.requestHeaderModifications = requestHeaderModifications;
    return this;
  }

  /**
   * Get requestHeaderModifications
   * @return requestHeaderModifications
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_HEADER_MODIFICATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RequestHeaderModifications getRequestHeaderModifications() {
    return requestHeaderModifications;
  }

  @JsonProperty(value = JSON_PROPERTY_REQUEST_HEADER_MODIFICATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestHeaderModifications(
      @jakarta.annotation.Nullable RequestHeaderModifications requestHeaderModifications) {
    this.requestHeaderModifications = requestHeaderModifications;
  }

  /**
   * Return true if this EventRuleActionAllow object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventRuleActionAllow eventRuleActionAllow = (EventRuleActionAllow) o;
    return Objects.equals(this.rulesetId, eventRuleActionAllow.rulesetId)
        && Objects.equals(this.ruleId, eventRuleActionAllow.ruleId)
        && Objects.equals(this.ruleExpression, eventRuleActionAllow.ruleExpression)
        && Objects.equals(this.type, eventRuleActionAllow.type)
        && Objects.equals(
            this.requestHeaderModifications, eventRuleActionAllow.requestHeaderModifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rulesetId, ruleId, ruleExpression, type, requestHeaderModifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventRuleActionAllow {\n");
    sb.append("    rulesetId: ").append(toIndentedString(rulesetId)).append("\n");
    sb.append("    ruleId: ").append(toIndentedString(ruleId)).append("\n");
    sb.append("    ruleExpression: ").append(toIndentedString(ruleExpression)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    requestHeaderModifications: ")
        .append(toIndentedString(requestHeaderModifications))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
