/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;

/**
 * LabelsInner
 */
@JsonPropertyOrder({
  LabelsInner.JSON_PROPERTY_LABEL,
  LabelsInner.JSON_PROPERTY_PREDICTION,
  LabelsInner.JSON_PROPERTY_ML_SCORE
})
@JsonTypeName("Labels_inner")
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.16.0")
public class LabelsInner {
  public static final String JSON_PROPERTY_LABEL = "label";
  @jakarta.annotation.Nonnull private String label;

  public static final String JSON_PROPERTY_PREDICTION = "prediction";
  @jakarta.annotation.Nullable private Boolean prediction;

  public static final String JSON_PROPERTY_ML_SCORE = "ml_score";
  @jakarta.annotation.Nullable private Double mlScore;

  public LabelsInner() {}

  public LabelsInner label(@jakarta.annotation.Nonnull String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLabel() {
    return label;
  }

  @JsonProperty(value = JSON_PROPERTY_LABEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(@jakarta.annotation.Nonnull String label) {
    this.label = label;
  }

  public LabelsInner prediction(@jakarta.annotation.Nullable Boolean prediction) {
    this.prediction = prediction;
    return this;
  }

  /**
   * Get prediction
   * @return prediction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREDICTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getPrediction() {
    return prediction;
  }

  @JsonProperty(value = JSON_PROPERTY_PREDICTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrediction(@jakarta.annotation.Nullable Boolean prediction) {
    this.prediction = prediction;
  }

  public LabelsInner mlScore(@jakarta.annotation.Nullable Double mlScore) {
    this.mlScore = mlScore;
    return this;
  }

  /**
   * Get mlScore
   * minimum: 0
   * maximum: 1
   * @return mlScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getMlScore() {
    return mlScore;
  }

  @JsonProperty(value = JSON_PROPERTY_ML_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMlScore(@jakarta.annotation.Nullable Double mlScore) {
    this.mlScore = mlScore;
  }

  /**
   * Return true if this Labels_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LabelsInner labelsInner = (LabelsInner) o;
    return Objects.equals(this.label, labelsInner.label)
        && Objects.equals(this.prediction, labelsInner.prediction)
        && Objects.equals(this.mlScore, labelsInner.mlScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, prediction, mlScore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LabelsInner {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    mlScore: ").append(toIndentedString(mlScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
