/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.v4.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.v4.sdk.JSON;


/**
 * PluginsInnerMimeTypesInner
 */
@JsonPropertyOrder({
  PluginsInnerMimeTypesInner.JSON_PROPERTY_TYPE,
  PluginsInnerMimeTypesInner.JSON_PROPERTY_SUFFIXES,
  PluginsInnerMimeTypesInner.JSON_PROPERTY_DESCRIPTION
})
@JsonTypeName("Plugins_inner_mimeTypes_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class PluginsInnerMimeTypesInner {
  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_SUFFIXES = "suffixes";
  @jakarta.annotation.Nullable
  private String suffixes;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public PluginsInnerMimeTypesInner() { 
  }

  public PluginsInnerMimeTypesInner type(@jakarta.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable String type) {
    this.type = type;
  }


  public PluginsInnerMimeTypesInner suffixes(@jakarta.annotation.Nullable String suffixes) {
    this.suffixes = suffixes;
    return this;
  }

  /**
   * Get suffixes
   * @return suffixes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUFFIXES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSuffixes() {
    return suffixes;
  }


  @JsonProperty(value = JSON_PROPERTY_SUFFIXES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuffixes(@jakarta.annotation.Nullable String suffixes) {
    this.suffixes = suffixes;
  }


  public PluginsInnerMimeTypesInner description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  /**
   * Return true if this Plugins_inner_mimeTypes_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PluginsInnerMimeTypesInner pluginsInnerMimeTypesInner = (PluginsInnerMimeTypesInner) o;
    return Objects.equals(this.type, pluginsInnerMimeTypesInner.type) &&
        Objects.equals(this.suffixes, pluginsInnerMimeTypesInner.suffixes) &&
        Objects.equals(this.description, pluginsInnerMimeTypesInner.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, suffixes, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PluginsInnerMimeTypesInner {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    suffixes: ").append(toIndentedString(suffixes)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

