/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * Proxy detection details (present if `proxy` is `true`)
 */
@JsonPropertyOrder({
  ProxyDetails.JSON_PROPERTY_PROXY_TYPE,
  ProxyDetails.JSON_PROPERTY_LAST_SEEN_AT,
  ProxyDetails.JSON_PROPERTY_PROVIDER
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.16.0")
public class ProxyDetails {
  /**
   * Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers
   */
  public enum ProxyTypeEnum {
    RESIDENTIAL(String.valueOf("residential")),

    DATA_CENTER(String.valueOf("data_center")),

    UNSUPPORTED_VALUE_SDK_UPGRADE_REQUIRED("unsupported_value_sdk_upgrade_required");

    private String value;

    ProxyTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ProxyTypeEnum fromValue(String value) {
      for (ProxyTypeEnum b : ProxyTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNSUPPORTED_VALUE_SDK_UPGRADE_REQUIRED;
    }
  }

  public static final String JSON_PROPERTY_PROXY_TYPE = "proxy_type";
  @jakarta.annotation.Nonnull private ProxyTypeEnum proxyType;

  public static final String JSON_PROPERTY_LAST_SEEN_AT = "last_seen_at";
  @jakarta.annotation.Nullable private Long lastSeenAt;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nullable private String provider;

  public ProxyDetails() {}

  public ProxyDetails proxyType(@jakarta.annotation.Nonnull ProxyTypeEnum proxyType) {
    this.proxyType = proxyType;
    return this;
  }

  /**
   * Residential proxies use real user IP addresses to appear as legitimate traffic,  while data center proxies are public proxies hosted in data centers
   * @return proxyType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROXY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ProxyTypeEnum getProxyType() {
    return proxyType;
  }

  @JsonProperty(value = JSON_PROPERTY_PROXY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProxyType(@jakarta.annotation.Nonnull ProxyTypeEnum proxyType) {
    this.proxyType = proxyType;
  }

  public ProxyDetails lastSeenAt(@jakarta.annotation.Nullable Long lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
    return this;
  }

  /**
   * Unix millisecond timestamp with hourly resolution of when this IP was last seen as a proxy
   * @return lastSeenAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getLastSeenAt() {
    return lastSeenAt;
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_SEEN_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSeenAt(@jakarta.annotation.Nullable Long lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
  }

  public ProxyDetails provider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * String representing the last proxy service provider detected when this IP was synced. An IP can be shared by multiple service providers.
   * @return provider
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProvider() {
    return provider;
  }

  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvider(@jakarta.annotation.Nullable String provider) {
    this.provider = provider;
  }

  /**
   * Return true if this ProxyDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProxyDetails proxyDetails = (ProxyDetails) o;
    return Objects.equals(this.proxyType, proxyDetails.proxyType)
        && Objects.equals(this.lastSeenAt, proxyDetails.lastSeenAt)
        && Objects.equals(this.provider, proxyDetails.provider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proxyType, lastSeenAt, provider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProxyDetails {\n");
    sb.append("    proxyType: ").append(toIndentedString(proxyType)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
