/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device.
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.fingerprint.v4.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Filter events by Device Rarity percentile bucket. `<p95` - device configuration is in the bottom 95% (most common). `p95-p99` - device is in the 95th to 99th percentile. `p99-p99.5` - device is in the 99th to 99.5th percentile. `p99.5-p99.9` - device is in the 99.5th to 99.9th percentile. `p99.9+` - device is in the top 0.1% (rarest). `not_seen` - device configuration has never been observed before.
 */
public enum SearchEventsRareDevicePercentileBucket {
  _P95("<p95"),

  P95_P99("p95-p99"),

  P99_P99_5("p99-p99.5"),

  P99_5_P99_9("p99.5-p99.9"),

  P99_9_("p99.9+"),

  NOT_SEEN("not_seen"),

  UNSUPPORTED_VALUE_SDK_UPGRADE_REQUIRED("unsupported_value_sdk_upgrade_required");

  private String value;

  SearchEventsRareDevicePercentileBucket(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SearchEventsRareDevicePercentileBucket fromValue(String value) {
    for (SearchEventsRareDevicePercentileBucket b :
        SearchEventsRareDevicePercentileBucket.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNSUPPORTED_VALUE_SDK_UPGRADE_REQUIRED;
  }
}
