/*
 * Server API
 * Fingerprint Server API allows you to get, search, and update Events in a server environment. It can be used for data exports, decision-making, and data analysis scenarios. Server API is intended for server-side usage, it's not intended to be used from the client side, whether it's a browser or a mobile device. 
 *
 * The version of the OpenAPI document: 4
 * Contact: support@fingerprint.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fingerprint.v4.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fingerprint.v4.sdk.JSON;


/**
 * Render and vendor strings reported by the WebGL context.
 */
@JsonPropertyOrder({
  WebGlBasics.JSON_PROPERTY_VERSION,
  WebGlBasics.JSON_PROPERTY_VENDOR,
  WebGlBasics.JSON_PROPERTY_VENDOR_UNMASKED,
  WebGlBasics.JSON_PROPERTY_RENDERER,
  WebGlBasics.JSON_PROPERTY_RENDERER_UNMASKED,
  WebGlBasics.JSON_PROPERTY_SHADING_LANGUAGE_VERSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class WebGlBasics {
  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private String version;

  public static final String JSON_PROPERTY_VENDOR = "vendor";
  @jakarta.annotation.Nullable
  private String vendor;

  public static final String JSON_PROPERTY_VENDOR_UNMASKED = "vendor_unmasked";
  @jakarta.annotation.Nullable
  private String vendorUnmasked;

  public static final String JSON_PROPERTY_RENDERER = "renderer";
  @jakarta.annotation.Nullable
  private String renderer;

  public static final String JSON_PROPERTY_RENDERER_UNMASKED = "renderer_unmasked";
  @jakarta.annotation.Nullable
  private String rendererUnmasked;

  public static final String JSON_PROPERTY_SHADING_LANGUAGE_VERSION = "shading_language_version";
  @jakarta.annotation.Nullable
  private String shadingLanguageVersion;

  public WebGlBasics() { 
  }

  public WebGlBasics version(@jakarta.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable String version) {
    this.version = version;
  }


  public WebGlBasics vendor(@jakarta.annotation.Nullable String vendor) {
    this.vendor = vendor;
    return this;
  }

  /**
   * Get vendor
   * @return vendor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VENDOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVendor() {
    return vendor;
  }


  @JsonProperty(value = JSON_PROPERTY_VENDOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVendor(@jakarta.annotation.Nullable String vendor) {
    this.vendor = vendor;
  }


  public WebGlBasics vendorUnmasked(@jakarta.annotation.Nullable String vendorUnmasked) {
    this.vendorUnmasked = vendorUnmasked;
    return this;
  }

  /**
   * Get vendorUnmasked
   * @return vendorUnmasked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VENDOR_UNMASKED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVendorUnmasked() {
    return vendorUnmasked;
  }


  @JsonProperty(value = JSON_PROPERTY_VENDOR_UNMASKED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVendorUnmasked(@jakarta.annotation.Nullable String vendorUnmasked) {
    this.vendorUnmasked = vendorUnmasked;
  }


  public WebGlBasics renderer(@jakarta.annotation.Nullable String renderer) {
    this.renderer = renderer;
    return this;
  }

  /**
   * Get renderer
   * @return renderer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RENDERER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRenderer() {
    return renderer;
  }


  @JsonProperty(value = JSON_PROPERTY_RENDERER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRenderer(@jakarta.annotation.Nullable String renderer) {
    this.renderer = renderer;
  }


  public WebGlBasics rendererUnmasked(@jakarta.annotation.Nullable String rendererUnmasked) {
    this.rendererUnmasked = rendererUnmasked;
    return this;
  }

  /**
   * Get rendererUnmasked
   * @return rendererUnmasked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RENDERER_UNMASKED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRendererUnmasked() {
    return rendererUnmasked;
  }


  @JsonProperty(value = JSON_PROPERTY_RENDERER_UNMASKED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRendererUnmasked(@jakarta.annotation.Nullable String rendererUnmasked) {
    this.rendererUnmasked = rendererUnmasked;
  }


  public WebGlBasics shadingLanguageVersion(@jakarta.annotation.Nullable String shadingLanguageVersion) {
    this.shadingLanguageVersion = shadingLanguageVersion;
    return this;
  }

  /**
   * Get shadingLanguageVersion
   * @return shadingLanguageVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHADING_LANGUAGE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShadingLanguageVersion() {
    return shadingLanguageVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_SHADING_LANGUAGE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShadingLanguageVersion(@jakarta.annotation.Nullable String shadingLanguageVersion) {
    this.shadingLanguageVersion = shadingLanguageVersion;
  }


  /**
   * Return true if this WebGlBasics object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebGlBasics webGlBasics = (WebGlBasics) o;
    return Objects.equals(this.version, webGlBasics.version) &&
        Objects.equals(this.vendor, webGlBasics.vendor) &&
        Objects.equals(this.vendorUnmasked, webGlBasics.vendorUnmasked) &&
        Objects.equals(this.renderer, webGlBasics.renderer) &&
        Objects.equals(this.rendererUnmasked, webGlBasics.rendererUnmasked) &&
        Objects.equals(this.shadingLanguageVersion, webGlBasics.shadingLanguageVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, vendor, vendorUnmasked, renderer, rendererUnmasked, shadingLanguageVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebGlBasics {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    vendorUnmasked: ").append(toIndentedString(vendorUnmasked)).append("\n");
    sb.append("    renderer: ").append(toIndentedString(renderer)).append("\n");
    sb.append("    rendererUnmasked: ").append(toIndentedString(rendererUnmasked)).append("\n");
    sb.append("    shadingLanguageVersion: ").append(toIndentedString(shadingLanguageVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

